import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export type ExportFormat = "csv" | "pdf" | "xlsx";

export type ReportCellValue = string | number | Array<string | number> | null | undefined;

export type ReportColumn<Row> = {
  label: string;
  value: (row: Row, index: number) => ReportCellValue;
  csvValue?: (row: Row, index: number) => ReportCellValue;
  pdfValue?: (row: Row, index: number) => ReportCellValue;
  xlsxValue?: (row: Row, index: number) => ReportCellValue;
  pdfWidth?: number;
  pdfAlign?: "left" | "center" | "right";
  preserveSpreadsheetText?: boolean;
  xlsxAlign?: "left" | "center" | "right";
  xlsxWidth?: number;
  xlsxMinWidth?: number;
  xlsxMaxWidth?: number;
  xlsxWrap?: boolean;
  xlsxType?: "text" | "currency" | "integer" | "decimal" | "date";
};

export type ReportExportConfig<Row> = {
  title: string;
  filenamePrefix: string;
  columns: ReportColumn<Row>[];
  orientation?: "portrait" | "landscape";
  logoUrl?: string;
  headerTitle?: string;
  footerText?: string;
  xlsxSheetName?: string;
  pdfUseUnicodeFont?: boolean;
};

export type ReportExportOptions<Row> = {
  config: ReportExportConfig<Row>;
  rows: Row[];
  filterSummaryLines?: string[];
  metadataLines?: string[];
  totalsRow?: ReportCellValue[];
  xlsxTotalsRow?: ReportCellValue[];
};

const DEFAULT_HEADER_TITLE = "Y-TRACE";
const DEFAULT_FOOTER_TEXT = "Generated by Y-TRACE";
const XLSX_CURRENCY_FORMAT = '"₱"#,##0.00';
const XLSX_DATE_FORMAT = "mmm d, yyyy";
const PDF_FONT_REGULAR_NAME = "SegoeUI";
const PDF_FONT_BOLD_NAME = "SegoeUIBold";
const PDF_FONT_REGULAR_URL = "/fonts/segoeui.ttf";
const PDF_FONT_BOLD_URL = "/fonts/segoeuib.ttf";
const PDF_COLORS = {
  darkBlue: [36, 96, 167] as const,
  lightBlue: [240, 244, 248] as const,
  border: [190, 198, 210] as const,
  divider: [210, 218, 226] as const,
  text: [32, 41, 57] as const,
  muted: [92, 102, 120] as const,
  zebra: [248, 250, 252] as const,
};

const formatFilenameDate = (date = new Date()) =>
  new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Manila",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(date);

export const getExportFilename = (filenamePrefix: string, format: ExportFormat) =>
  `${filenamePrefix}-${formatFilenameDate()}.${format}`;

export const formatReportGeneratedAt = (date = new Date()) =>
  new Intl.DateTimeFormat("en-PH", {
    timeZone: "Asia/Manila",
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(date);

export const formatDateDisplay = (value?: string | null) => {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  return new Intl.DateTimeFormat("en-PH", {
    timeZone: "Asia/Manila",
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(date);
};

export const formatCurrencyCsv = (value: number) => Number(value || 0).toFixed(2);

export const formatCurrencyPdf = (value: number) => `₱${Number(value || 0).toLocaleString("en-PH", {
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
})}`;

export const getExcelColumnLetter = (columnNumber: number) => {
  let result = "";
  let value = columnNumber;

  while (value > 0) {
    const remainder = (value - 1) % 26;
    result = String.fromCharCode(65 + remainder) + result;
    value = Math.floor((value - 1) / 26);
  }

  return result;
};

const collapseWhitespace = (value: string) => value.replace(/\s+/g, " ").trim();

const normalizeCellParts = (value: ReportCellValue): string[] => {
  if (value == null) return [""];
  const parts = Array.isArray(value) ? value : [value];
  const normalized = parts
    .flatMap((part) => String(part).split(/\r?\n/g))
    .map((part) => collapseWhitespace(part))
    .filter((part) => part.length > 0);
  return normalized.length ? normalized : [""];
};

const sanitizeForSpreadsheet = (value: string, preserveSpreadsheetText?: boolean) => {
  if (!value) return "";

  const looksLikeNumericText = /^[+]?[\d\s().-]+$/.test(value);
  const startsDangerously = /^[=+\-@]/.test(value);

  if (preserveSpreadsheetText && looksLikeNumericText) {
    return `'${value}`;
  }

  if (startsDangerously) {
    return `'${value}`;
  }

  return value;
};

const toCsvCell = (value: string) => `"${value.replace(/"/g, "\"\"")}"`;
const toPdfCell = (value: ReportCellValue) => normalizeCellParts(value).join("\n");

const downloadBlob = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

const blobToDataUrl = (blob: Blob) =>
  new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(String(reader.result));
    reader.onerror = () => reject(reader.error ?? new Error("Failed to read blob."));
    reader.readAsDataURL(blob);
  });

const arrayBufferToBase64 = (buffer: ArrayBuffer) => {
  const bytes = new Uint8Array(buffer);
  const chunkSize = 0x8000;
  let binary = "";
  for (let i = 0; i < bytes.length; i += chunkSize) {
    const chunk = bytes.subarray(i, i + chunkSize);
    binary += String.fromCharCode(...chunk);
  }
  return btoa(binary);
};

const loadLogoDataUrl = async (logoUrl?: string) => {
  if (!logoUrl) return null;
  try {
    const response = await fetch(logoUrl);
    if (!response.ok) return null;
    const blob = await response.blob();
    return await blobToDataUrl(blob);
  } catch {
    return null;
  }
};

const ensurePdfFonts = async (doc: jsPDF) => {
  const fontState = doc as jsPDF & { __yTraceFontsLoaded?: boolean };
  if (fontState.__yTraceFontsLoaded) return;

  const [regularResponse, boldResponse] = await Promise.all([
    fetch(PDF_FONT_REGULAR_URL),
    fetch(PDF_FONT_BOLD_URL),
  ]);

  if (!regularResponse.ok || !boldResponse.ok) {
    fontState.__yTraceFontsLoaded = true;
    return;
  }

  const [regularBuffer, boldBuffer] = await Promise.all([
    regularResponse.arrayBuffer(),
    boldResponse.arrayBuffer(),
  ]);

  doc.addFileToVFS("segoeui.ttf", arrayBufferToBase64(regularBuffer));
  doc.addFont("segoeui.ttf", PDF_FONT_REGULAR_NAME, "normal");
  doc.addFileToVFS("segoeuib.ttf", arrayBufferToBase64(boldBuffer));
  doc.addFont("segoeuib.ttf", PDF_FONT_BOLD_NAME, "bold");
  fontState.__yTraceFontsLoaded = true;
};

export const buildCsvContent = <Row,>({ config, rows, totalsRow }: ReportExportOptions<Row>) => {
  const headerRow = config.columns.map((column) => toCsvCell(column.label));
  const bodyRows = rows.map((row, index) =>
    config.columns.map((column) => {
      const joinedValue = normalizeCellParts((column.csvValue ?? column.value)(row, index)).join("; ");
      return toCsvCell(sanitizeForSpreadsheet(joinedValue, column.preserveSpreadsheetText));
    }),
  );

  const footerRows = totalsRow
    ? [
        totalsRow.map((cell, index) => {
          const joinedValue = normalizeCellParts(cell).join("; ");
          return toCsvCell(sanitizeForSpreadsheet(joinedValue, config.columns[index]?.preserveSpreadsheetText));
        }),
      ]
    : [];

  return `\uFEFF${[headerRow, ...bodyRows, ...footerRows].map((row) => row.join(",")).join("\r\n")}`;
};

type PdfHeaderLayout = {
  headerTitle: string;
  reportTitle: string;
  footerText: string;
  logoDataUrl: string | null;
  detailLines: string[];
  pageWidth: number;
  pageHeight: number;
  marginLeft: number;
  marginRight: number;
  dividerY: number;
  startY: number;
};

const buildPdfHeaderLayout = async <Row,>(
  doc: jsPDF,
  options: ReportExportOptions<Row>,
  marginLeft: number,
  marginRight: number,
) => {
  const { config, metadataLines = [], filterSummaryLines = [] } = options;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const logoDataUrl = await loadLogoDataUrl(config.logoUrl);
  const detailLines = [`Generated: ${formatReportGeneratedAt()}`, ...metadataLines, ...filterSummaryLines];

  const detailWidth = pageWidth - marginLeft - marginRight;
  const headerTopY = 28;
  const reportTitleY = headerTopY + 42;
  let currentY = reportTitleY + 18;

  doc.setFont(options.config.pdfUseUnicodeFont ? PDF_FONT_REGULAR_NAME : "helvetica", "normal");
  doc.setFontSize(9);
  doc.setCharSpace(0);
  detailLines.forEach((line) => {
    const wrappedLines = doc.splitTextToSize(line, detailWidth) as string[];
    currentY += wrappedLines.length * 11;
  });

  const dividerY = currentY + 6;
  return {
    headerTitle: config.headerTitle ?? DEFAULT_HEADER_TITLE,
    reportTitle: config.title,
    footerText: config.footerText ?? DEFAULT_FOOTER_TEXT,
    logoDataUrl,
    detailLines,
    pageWidth,
    pageHeight,
    marginLeft,
    marginRight,
    dividerY,
    startY: dividerY + 8,
  };
};

const renderPdfHeader = (doc: jsPDF, layout: PdfHeaderLayout) => {
  const headerTopY = 28;
  doc.setCharSpace(0);

  if (layout.logoDataUrl) {
    try {
      doc.addImage(layout.logoDataUrl, "PNG", layout.marginLeft, headerTopY - 2, 32, 32);
    } catch {
      // Ignore image errors and continue with text-only header.
    }
  }

  const titleOffsetX = layout.marginLeft + (layout.logoDataUrl ? 42 : 0);

  const regularFont = (doc as jsPDF & { __yTraceUseUnicodeFont?: boolean }).__yTraceUseUnicodeFont ? PDF_FONT_REGULAR_NAME : "helvetica";
  const boldFont = (doc as jsPDF & { __yTraceUseUnicodeFont?: boolean }).__yTraceUseUnicodeFont ? PDF_FONT_BOLD_NAME : "helvetica";

  doc.setFont(boldFont, "bold");
  doc.setFontSize(14);
  doc.setTextColor(...PDF_COLORS.text);
  doc.text(layout.headerTitle, titleOffsetX, headerTopY + 10);

  doc.setFont(boldFont, "bold");
  doc.setFontSize(15);
  doc.text(layout.reportTitle, layout.marginLeft, headerTopY + 42);

  doc.setFont(regularFont, "normal");
  doc.setFontSize(9);
  doc.setTextColor(...PDF_COLORS.muted);

  let currentY = headerTopY + 60;
  const detailWidth = layout.pageWidth - layout.marginLeft - layout.marginRight;
  layout.detailLines.forEach((line) => {
    const wrappedLines = doc.splitTextToSize(line, detailWidth) as string[];
    doc.text(wrappedLines, layout.marginLeft, currentY);
    currentY += wrappedLines.length * 11;
  });

  doc.setDrawColor(...PDF_COLORS.divider);
  doc.setLineWidth(0.8);
  doc.line(layout.marginLeft, layout.dividerY, layout.pageWidth - layout.marginRight, layout.dividerY);

  doc.setFontSize(8);
  doc.setTextColor(...PDF_COLORS.muted);
  doc.text(layout.footerText, layout.marginLeft, layout.pageHeight - 18);
};

export const exportReportAsCsv = async <Row,>(options: ReportExportOptions<Row>) => {
  const filename = getExportFilename(options.config.filenamePrefix, "csv");
  const csvContent = buildCsvContent(options);
  downloadBlob(new Blob([csvContent], { type: "text/csv;charset=utf-8;" }), filename);
};

export const exportReportAsPdf = async <Row,>(options: ReportExportOptions<Row>) => {
  const { config, rows, totalsRow } = options;
  const doc = new jsPDF({
    orientation: config.orientation ?? "landscape",
    unit: "pt",
    format: "a4",
  });

  const useUnicodeFont = Boolean(config.pdfUseUnicodeFont);
  if (useUnicodeFont) {
    await ensurePdfFonts(doc);
  }
  (doc as jsPDF & { __yTraceUseUnicodeFont?: boolean }).__yTraceUseUnicodeFont = useUnicodeFont;
  doc.setFont(useUnicodeFont ? PDF_FONT_REGULAR_NAME : "helvetica", "normal");
  doc.setCharSpace(0);

  const marginLeft = 36;
  const marginRight = 36;
  const marginBottom = 42;
  const headerLayout = await buildPdfHeaderLayout(doc, options, marginLeft, marginRight);

  autoTable(doc, {
    startY: headerLayout.startY,
    margin: {
      top: headerLayout.startY,
      right: marginRight,
      bottom: marginBottom,
      left: marginLeft,
    },
    head: [config.columns.map((column) => column.label)],
    body: rows.map((row, index) =>
      config.columns.map((column) => toPdfCell((column.pdfValue ?? column.value)(row, index))),
    ),
    foot: totalsRow ? [totalsRow.map((cell) => toPdfCell(cell))] : undefined,
    showFoot: totalsRow ? "lastPage" : "never",
    theme: "grid",
    styles: {
      fontSize: 9,
      cellPadding: { top: 5, right: 5, bottom: 5, left: 5 },
      lineColor: [...PDF_COLORS.border],
      lineWidth: 0.6,
      textColor: [...PDF_COLORS.text],
      valign: "middle",
      overflow: "linebreak",
      font: useUnicodeFont ? PDF_FONT_REGULAR_NAME : "helvetica",
      fontStyle: "normal",
    },
    headStyles: {
      fillColor: [...PDF_COLORS.darkBlue],
      textColor: [255, 255, 255],
      font: useUnicodeFont ? PDF_FONT_BOLD_NAME : "helvetica",
      fontStyle: "bold",
      halign: "left",
      valign: "middle",
    },
    footStyles: {
      fillColor: [...PDF_COLORS.lightBlue],
      textColor: [...PDF_COLORS.text],
      font: useUnicodeFont ? PDF_FONT_BOLD_NAME : "helvetica",
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [...PDF_COLORS.zebra],
    },
    columnStyles: Object.fromEntries(
      config.columns.map((column, index) => [
        index,
        {
          cellWidth: column.pdfWidth ?? "auto",
          halign: column.pdfAlign ?? "left",
          valign: "middle",
        },
      ]),
    ),
    didDrawPage: ({ pageNumber }) => {
      renderPdfHeader(doc, headerLayout);
      doc.setFont(useUnicodeFont ? PDF_FONT_REGULAR_NAME : "helvetica", "normal");
      doc.setCharSpace(0);
      doc.setFontSize(8);
      doc.setTextColor(...PDF_COLORS.muted);
      doc.text(`Page ${pageNumber}`, headerLayout.pageWidth - marginRight, headerLayout.pageHeight - 18, {
        align: "right",
      });
    },
  });

  doc.save(getExportFilename(config.filenamePrefix, "pdf"));
};

const calculateColumnWidth = (values: string[], minWidth: number, maxWidth: number) => {
  const longest = values.reduce((max, value) => Math.max(max, String(value ?? "").length), 0);
  return Math.min(Math.max(longest + 2, minWidth), maxWidth);
};

type ExcelJsModuleShape = {
  Workbook?: new () => {
    creator?: string;
    created?: Date;
    addWorksheet: (name: string) => ExcelWorksheetShape;
    xlsx: { writeBuffer: () => Promise<ArrayBuffer> };
  };
  default?: ExcelJsModuleShape;
};

type ExcelWorksheetShape = {
  mergeCells: (range: string) => void;
  getCell: (reference: string) => ExcelCellShape;
  getRow: (index: number) => ExcelRowShape;
  columns: Array<{ width?: number }>;
  autoFilter?: { from: string; to: string };
  views?: Array<{ state: string; ySplit: number }>;
  pageSetup?: {
    orientation: "portrait" | "landscape";
    fitToPage: boolean;
    fitToWidth: number;
    fitToHeight: number;
    printArea: string;
    printTitlesRow: string;
    margins: {
      left: number;
      right: number;
      top: number;
      bottom: number;
      header: number;
      footer: number;
    };
  };
};

type ExcelRowShape = {
  height?: number;
  getCell: (index: number) => ExcelCellShape;
};

type ExcelCellShape = {
  value: unknown;
  font?: Record<string, unknown>;
  alignment?: Record<string, unknown>;
  fill?: Record<string, unknown>;
  border?: Record<string, unknown>;
  numFmt?: string;
};

const resolveExcelJsWorkbook = async () => {
  const excelJsModule = (await import("exceljs")) as ExcelJsModuleShape;
  const workbookCtor = excelJsModule.Workbook ?? excelJsModule.default?.Workbook;

  if (!workbookCtor) {
    throw new Error("ExcelJS workbook constructor is unavailable.");
  }

  return workbookCtor;
};

const getWorksheetCellValue = <Row,>(column: ReportColumn<Row>, row: Row, index: number) => {
  const rawValue = (column.xlsxValue ?? column.value)(row, index);
  if (column.xlsxType === "currency" || column.xlsxType === "integer" || column.xlsxType === "decimal") {
    if (typeof rawValue === "number") return rawValue;
    const numeric = Number(Array.isArray(rawValue) ? rawValue[0] ?? 0 : rawValue ?? 0);
    return Number.isFinite(numeric) ? numeric : 0;
  }

  if (column.xlsxType === "date") {
    const dateValue = Array.isArray(rawValue) ? rawValue[0] : rawValue;
    if (!dateValue) return "";
    const date = new Date(String(dateValue));
    return Number.isNaN(date.getTime()) ? "" : date;
  }

  const separator = column.xlsxWrap ? "\n" : "; ";
  return normalizeCellParts(rawValue).join(separator);
};

const estimateRowHeight = (values: unknown[]) => {
  const lineCount = values.reduce((max, value) => {
    const text = String(value ?? "");
    const lines = text.split("\n").length;
    return Math.max(max, lines);
  }, 1);
  return Math.max(22, lineCount * 16);
};

export const exportReportAsXlsx = async <Row,>(options: ReportExportOptions<Row>) => {
  const Workbook = await resolveExcelJsWorkbook();
  const workbook = new Workbook();
  workbook.creator = "OpenAI Codex";
  workbook.created = new Date();

  const { config, rows, metadataLines = [], filterSummaryLines = [], xlsxTotalsRow } = options;
  const worksheet = workbook.addWorksheet(config.xlsxSheetName ?? config.title);
  const totalColumns = config.columns.length;
  const lastColumnLetter = getExcelColumnLetter(totalColumns);

  let currentRow = 1;
  worksheet.mergeCells(`A${currentRow}:${lastColumnLetter}${currentRow}`);
  const titleCell = worksheet.getCell(`A${currentRow}`);
  titleCell.value = config.headerTitle ?? DEFAULT_HEADER_TITLE;
  titleCell.font = { bold: true, size: 14, color: { argb: "202939" } };
  titleCell.alignment = { vertical: "middle", horizontal: "left" };
  worksheet.getRow(currentRow).height = 22;

  currentRow += 1;
  worksheet.mergeCells(`A${currentRow}:${lastColumnLetter}${currentRow}`);
  const subtitleCell = worksheet.getCell(`A${currentRow}`);
  subtitleCell.value = config.title;
  subtitleCell.font = { bold: true, size: 12, color: { argb: "202939" } };
  subtitleCell.alignment = { vertical: "middle", horizontal: "left" };
  worksheet.getRow(currentRow).height = 20;

  const summaryLines = [`Generated: ${formatReportGeneratedAt()}`, ...metadataLines, ...filterSummaryLines];
  summaryLines.forEach((line) => {
    currentRow += 1;
    worksheet.mergeCells(`A${currentRow}:${lastColumnLetter}${currentRow}`);
    const lineCell = worksheet.getCell(`A${currentRow}`);
    lineCell.value = line;
    lineCell.font = { size: 10, color: { argb: "5C6678" } };
    lineCell.alignment = { vertical: "middle", horizontal: "left", wrapText: true };
    worksheet.getRow(currentRow).height = 18;
  });

  currentRow += 1;
  const headerRowNumber = currentRow;
  const headerRow = worksheet.getRow(headerRowNumber);
  headerRow.height = 28;

  config.columns.forEach((column, columnIndex) => {
    const cell = headerRow.getCell(columnIndex + 1);
    cell.value = column.label;
    cell.font = { bold: true, color: { argb: "FFFFFF" } };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "2460A7" },
    };
    cell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
    cell.border = {
      top: { style: "thin", color: { argb: "BEC6D2" } },
      left: { style: "thin", color: { argb: "BEC6D2" } },
      bottom: { style: "thin", color: { argb: "BEC6D2" } },
      right: { style: "thin", color: { argb: "BEC6D2" } },
    };
  });

  rows.forEach((row, index) => {
    const rowNumber = headerRowNumber + index + 1;
    const dataRow = worksheet.getRow(rowNumber);
    const rowValues = config.columns.map((column) => getWorksheetCellValue(column, row, index));
    dataRow.height = estimateRowHeight(rowValues);

    config.columns.forEach((column, columnIndex) => {
      const cell = dataRow.getCell(columnIndex + 1);
      cell.value = rowValues[columnIndex] as never;
      cell.alignment = {
        vertical: "middle",
        horizontal:
          column.xlsxAlign ??
          (column.pdfAlign === "right" ? "right" : column.pdfAlign === "center" ? "center" : "left"),
        wrapText: column.xlsxWrap ?? true,
      };
      cell.border = {
        top: { style: "thin", color: { argb: "D2DAE2" } },
        left: { style: "thin", color: { argb: "D2DAE2" } },
        bottom: { style: "thin", color: { argb: "D2DAE2" } },
        right: { style: "thin", color: { argb: "D2DAE2" } },
      };
      if (index % 2 === 1) {
        cell.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: "F8FAFC" },
        };
      }
      if (column.xlsxType === "currency") cell.numFmt = XLSX_CURRENCY_FORMAT;
      if (column.xlsxType === "integer") cell.numFmt = "0";
      if (column.xlsxType === "decimal") cell.numFmt = "0.00";
      if (column.xlsxType === "date" && rowValues[columnIndex] instanceof Date) cell.numFmt = XLSX_DATE_FORMAT;
      if (column.xlsxType === "text" || column.preserveSpreadsheetText) cell.numFmt = "@";
    });
  });

  if (xlsxTotalsRow?.length) {
    const totalsRowNumber = headerRowNumber + rows.length + 1;
    const totalsRow = worksheet.getRow(totalsRowNumber);
    totalsRow.height = 22;

    config.columns.forEach((column, columnIndex) => {
      const cell = totalsRow.getCell(columnIndex + 1);
      cell.value = (xlsxTotalsRow[columnIndex] ?? "") as never;
      cell.font = { bold: true, color: { argb: "202939" } };
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "F0F4F8" },
      };
      cell.alignment = {
        vertical: "middle",
        horizontal:
          column.xlsxAlign ??
          (column.pdfAlign === "right" ? "right" : column.pdfAlign === "center" ? "center" : "left"),
        wrapText: column.xlsxWrap ?? true,
      };
      cell.border = {
        top: { style: "thin", color: { argb: "BEC6D2" } },
        left: { style: "thin", color: { argb: "BEC6D2" } },
        bottom: { style: "thin", color: { argb: "BEC6D2" } },
        right: { style: "thin", color: { argb: "BEC6D2" } },
      };
      if (column.xlsxType === "currency") cell.numFmt = XLSX_CURRENCY_FORMAT;
      if (column.xlsxType === "integer") cell.numFmt = "0";
      if (column.xlsxType === "decimal") cell.numFmt = "0.00";
      if (column.xlsxType === "text" || column.preserveSpreadsheetText) cell.numFmt = "@";
    });
  }

  worksheet.columns = config.columns.map((column, columnIndex) => {
    const values = [
      column.label,
      ...rows.map((row, rowIndex) => {
        const value = getWorksheetCellValue(column, row, rowIndex);
        return value instanceof Date ? formatDateDisplay(value.toISOString()) : String(value ?? "");
      }),
      ...(xlsxTotalsRow ? [String(xlsxTotalsRow[columnIndex] ?? "")] : []),
    ];
    return {
      width:
        column.xlsxWidth ??
        calculateColumnWidth(values, column.xlsxMinWidth ?? 12, column.xlsxMaxWidth ?? 40),
    };
  });

  const lastDataRow = headerRowNumber + rows.length + (xlsxTotalsRow?.length ? 1 : 0);
  worksheet.autoFilter = {
    from: `A${headerRowNumber}`,
    to: `${lastColumnLetter}${headerRowNumber}`,
  };
  worksheet.views = [{ state: "frozen", ySplit: headerRowNumber }];
  worksheet.pageSetup = {
    orientation: config.orientation === "portrait" ? "portrait" : "landscape",
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    printArea: `A1:${lastColumnLetter}${lastDataRow}`,
    printTitlesRow: `${headerRowNumber}:${headerRowNumber}`,
    margins: {
      left: 0.3,
      right: 0.3,
      top: 0.4,
      bottom: 0.4,
      header: 0.2,
      footer: 0.2,
    },
  };

  const buffer = await workbook.xlsx.writeBuffer();
  downloadBlob(
    new Blob([buffer], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    }),
    getExportFilename(config.filenamePrefix, "xlsx"),
  );
};

export const exportReport = async <Row,>(format: ExportFormat, options: ReportExportOptions<Row>) => {
  if (format === "csv") {
    await exportReportAsCsv(options);
    return;
  }

  if (format === "xlsx") {
    await exportReportAsXlsx(options);
    return;
  }

  await exportReportAsPdf(options);
};
