-- Run this in the Supabase SQL editor.
-- Sets up the backend for the new Administrators (Accounts) page:
-- a units table, admin_accounts.role_id/unit_id linkage, and the RPCs the
-- admin portal needs to list/create/edit/suspend/delete administrators.
--
-- CONFIRMED: the `roles.code` column is typed `app_role_code`, a Postgres
-- enum shared with the rest of the app (it also holds 'organization_user'
-- and 'youth'). It only had 'admin' — no 'super_admin' — so STEP 1 below
-- adds that value to the enum.
--
-- >>> RUN STEP 1 BY ITSELF FIRST, THEN RUN STEP 2 (everything else) <<<
-- Postgres will not let a newly added enum value be used in the same
-- transaction/script that added it, so these must be two separate
-- SQL editor runs or you'll get an "unsafe use of new value" error.
--
-- ASSUMPTION: password_hash is verified with pgcrypto bcrypt
-- (crypt(password, password_hash) = password_hash). If your login RPC uses
-- something else, create_admin_account below will produce accounts that
-- can't log in — let me know and I'll adjust.
--
-- SECURITY: every mutating RPC below (create/update/suspend/delete) requires
-- the caller to hold the 'super_admin' role, not just any authenticated
-- admin session — otherwise a freshly created low-privilege Admin account
-- could create other accounts, delete admins, or escalate its own role.
-- update_admin_account additionally blocks a caller from changing their own
-- role_id, so a super admin can't accidentally (or a compromised session
-- can't deliberately) demote themselves out of the only account that can
-- still manage roles.

-- ============================================================
-- STEP 1 — run this statement alone, then come back for STEP 2.
-- ============================================================
alter type public.app_role_code add value if not exists 'super_admin';

-- ============================================================
-- STEP 2 — run everything below this line after STEP 1 has
-- completed (in a separate query execution).
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.units (
  id smallint generated by default as identity not null,
  code text not null,
  label text not null,
  description text null,
  created_at timestamp with time zone not null default now(),
  constraint units_pkey primary key (id),
  constraint units_code_key unique (code)
);

insert into public.units (code, label)
values
  ('administration_finance', 'Administration & Finance'),
  ('programs_operations', 'Programs & Operations'),
  ('policy_planning_monitoring', 'Policy, Planning, & Monitoring')
on conflict (code) do nothing;

insert into public.roles (code, label)
values
  ('super_admin', 'Super Admin'),
  ('admin', 'Admin')
on conflict (code) do nothing;

alter table public.admin_accounts
  add column if not exists role_id smallint references public.roles(id),
  add column if not exists unit_id smallint references public.units(id);

create or replace function public.list_roles_for_admin_portal(_session_token text)
returns table (id smallint, code text, label text)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  return query
  select r.id, r.code::text, r.label from public.roles r order by r.id asc;
end;
$$;

create or replace function public.list_units_for_admin_portal(_session_token text)
returns table (id smallint, code text, label text)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  return query
  select u.id, u.code, u.label from public.units u order by u.id asc;
end;
$$;

create or replace function public.list_administrators_for_admin_portal(_session_token text)
returns table (
  id uuid,
  display_name text,
  email text,
  username text,
  role_code text,
  role_label text,
  unit_code text,
  unit_label text,
  is_active boolean,
  last_active_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  return query
  select
    aa.id,
    aa.display_name,
    aa.email::text,
    aa.username::text,
    r.code::text,
    r.label,
    u.code,
    u.label,
    aa.is_active,
    (select max(s.last_used_at) from public.admin_sessions s where s.admin_id = aa.id)
  from public.admin_accounts aa
  left join public.roles r on r.id = aa.role_id
  left join public.units u on u.id = aa.unit_id
  order by aa.display_name asc;
end;
$$;

create or replace function public.create_admin_account(
  _session_token text,
  _display_name text,
  _email text,
  _username text,
  _password text,
  _role_id smallint,
  _unit_id smallint
)
returns table (id uuid, display_name text, email text, username text, role_id smallint, unit_id smallint, is_active boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  if not exists (
    select 1 from public.admin_accounts a
    join public.roles r on r.id = a.role_id
    where a.id = _admin_id and r.code = 'super_admin'
  ) then
    raise exception 'Only super administrators may manage admin accounts.';
  end if;

  return query
  insert into public.admin_accounts (display_name, email, username, password_hash, role_id, unit_id)
  values (
    trim(_display_name),
    trim(_email),
    trim(_username),
    crypt(_password, gen_salt('bf')),
    _role_id,
    _unit_id
  )
  returning admin_accounts.id, admin_accounts.display_name, admin_accounts.email::text, admin_accounts.username::text, admin_accounts.role_id, admin_accounts.unit_id, admin_accounts.is_active;
end;
$$;

create or replace function public.update_admin_account(
  _session_token text,
  _admin_id_to_update uuid,
  _display_name text,
  _email text,
  _username text,
  _role_id smallint,
  _unit_id smallint
)
returns table (id uuid, display_name text, email text, username text, role_id smallint, unit_id smallint, is_active boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  if not exists (
    select 1 from public.admin_accounts a
    join public.roles r on r.id = a.role_id
    where a.id = _admin_id and r.code = 'super_admin'
  ) then
    raise exception 'Only super administrators may manage admin accounts.';
  end if;

  if _admin_id = _admin_id_to_update and _role_id is distinct from (select role_id from public.admin_accounts where id = _admin_id) then
    raise exception 'You cannot change your own role.';
  end if;

  return query
  update public.admin_accounts
  set
    display_name = trim(_display_name),
    email = trim(_email),
    username = trim(_username),
    role_id = _role_id,
    unit_id = _unit_id,
    updated_at = now()
  where admin_accounts.id = _admin_id_to_update
  returning admin_accounts.id, admin_accounts.display_name, admin_accounts.email::text, admin_accounts.username::text, admin_accounts.role_id, admin_accounts.unit_id, admin_accounts.is_active;
end;
$$;

create or replace function public.set_admin_account_active(
  _session_token text,
  _admin_id_to_update uuid,
  _is_active boolean
)
returns table (id uuid, display_name text, email text, username text, role_id smallint, unit_id smallint, is_active boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  if not exists (
    select 1 from public.admin_accounts a
    join public.roles r on r.id = a.role_id
    where a.id = _admin_id and r.code = 'super_admin'
  ) then
    raise exception 'Only super administrators may manage admin accounts.';
  end if;

  if _admin_id = _admin_id_to_update and not _is_active then
    raise exception 'You cannot suspend your own account.';
  end if;

  return query
  update public.admin_accounts
  set is_active = _is_active, updated_at = now()
  where admin_accounts.id = _admin_id_to_update
  returning admin_accounts.id, admin_accounts.display_name, admin_accounts.email::text, admin_accounts.username::text, admin_accounts.role_id, admin_accounts.unit_id, admin_accounts.is_active;
end;
$$;

create or replace function public.delete_admin_account(
  _session_token text,
  _admin_id_to_delete uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  if not exists (
    select 1 from public.admin_accounts a
    join public.roles r on r.id = a.role_id
    where a.id = _admin_id and r.code = 'super_admin'
  ) then
    raise exception 'Only super administrators may manage admin accounts.';
  end if;

  if _admin_id = _admin_id_to_delete then
    raise exception 'You cannot delete your own account.';
  end if;

  delete from public.admin_accounts where admin_accounts.id = _admin_id_to_delete;
end;
$$;
