-- LYDO Connect all-in-one schema
-- New organization-focused system for registration, documents, budget requests, liquidation, news, transparency, remarks, notifications, and audit logging.

-- ============================================================================
-- Extensions
-- ============================================================================

create extension if not exists pgcrypto;
create extension if not exists citext;

-- ============================================================================
-- Enums
-- ============================================================================

do $$ begin
  create type public.app_role_code as enum ('admin', 'organization_user', 'youth');
exception
  when duplicate_object then null;
end $$;


do $$ begin
  create type public.profile_status as enum ('incomplete', 'pending_review', 'verified', 'needs_update', 'suspended_inactive');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.document_submission_status as enum (
    'not_started',
    'draft',
    'uploaded',
    'ocr_processing',
    'ready_for_review',
    'submitted',
    'under_admin_review',
    'needs_revision',
    'approved_green',
    'rejected_red'
  );
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.document_file_validation_status as enum ('correct', 'needs_reupload', 'missing', 'mismatch');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.ocr_status as enum ('pending', 'processing', 'completed', 'failed');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.budget_request_status as enum (
    'draft',
    'submitted',
    'under_review',
    'needs_revision',
    'approved_for_ftf_green',
    'rejected_red',
    'hard_copy_submitted',
    'budget_released',
    'completed'
  );
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.liquidation_report_status as enum (
    'pending_activity_completion',
    'not_started',
    'draft',
    'submitted',
    'under_review',
    'needs_revision',
    'approved_for_ftf_green',
    'rejected_red',
    'hard_copy_submitted',
    'completed_liquidated',
    'overdue'
  );
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.visibility_status as enum ('draft', 'published', 'hidden');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.compliance_remark_status as enum ('open', 'resolved');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.notification_type as enum (
    'document_revision',
    'document_green',
    'document_red',
    'budget_go_signal',
    'budget_revision',
    'budget_released',
    'liquidation_go_signal',
    'liquidation_revision',
    'overdue',
    'completed',
    'news_release'
  );
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.activity_action as enum (
    'created_profile',
    'updated_profile',
    'submitted_documents',
    'reviewed_documents',
    'submitted_budget_request',
    'reviewed_budget_request',
    'submitted_liquidation_report',
    'reviewed_liquidation_report',
    'published_news_release',
    'published_transparency_post',
    'added_remark',
    'resolved_remark'
  );
exception
  when duplicate_object then null;
end $$;

-- ============================================================================
-- Tables
-- ============================================================================

create table if not exists public.roles (
  id smallint generated by default as identity primary key,
  code public.app_role_code not null unique,
  label text not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role_id smallint not null references public.roles(id) on delete restrict,
  assigned_at timestamptz not null default now(),
  assigned_by uuid references auth.users(id) on delete set null,
  primary key (user_id, role_id)
);

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email citext not null unique,
  full_name text,
  display_name text,
  contact_number text,
  municipality text,
  barangay text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_accounts (
  id uuid primary key default gen_random_uuid(),
  username citext not null unique,
  password_hash text not null,
  email citext not null unique,
  display_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_sessions (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid not null references public.admin_accounts(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  last_used_at timestamptz not null default now(),
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.policy_versions (
  id uuid primary key default gen_random_uuid(),
  version text not null unique,
  title text not null,
  terms_content text not null,
  privacy_content text not null,
  is_active boolean not null default false,
  effective_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_policy_acceptance (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  policy_version_id uuid not null references public.policy_versions(id) on delete restrict,
  accepted_terms boolean not null default true,
  accepted_privacy boolean not null default true,
  accepted_at timestamptz not null default now(),
  accepted_ip text,
  user_agent text,
  created_at timestamptz not null default now(),
  constraint uq_user_policy_acceptance unique (user_id, policy_version_id)
);

create table if not exists public.barangays (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organization_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  organization_name text not null,
  organization_email citext not null,
  contact_number text not null,
  district text not null default '',
  barangay text not null,
  is_existing_organization boolean not null default false,
  organization_identifier_number text not null default '',
  major_classification text not null default '',
  sub_classification text not null default '',
  advocacies text[] not null default '{}'::text[],
  adviser_name text,
  representative_name text,
  address text,
  facebook_page_url text,
  profile_status public.profile_status not null default 'incomplete',
  verified_at timestamptz,
  internal_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint organization_profiles_contact_number_check check (contact_number ~ '^09[0-9]{9}$')
);

-- Compatibility repair for older projects where organization_profiles already exists
-- but is missing newer organization workflow columns.
alter table if exists public.organization_profiles
  add column if not exists organization_email citext,
  add column if not exists major_classification text,
  add column if not exists sub_classification text,
  add column if not exists district text not null default '',
  add column if not exists is_existing_organization boolean not null default false,
  add column if not exists organization_identifier_number text not null default '',
  add column if not exists advocacies text[],
  add column if not exists adviser_name text,
  add column if not exists representative_name text,
  add column if not exists address text,
  add column if not exists facebook_page_url text,
  add column if not exists profile_status public.profile_status,
  add column if not exists verified_at timestamptz,
  add column if not exists internal_notes text;

update public.organization_profiles
set
  is_existing_organization = coalesce(is_existing_organization, false),
  organization_identifier_number = coalesce(organization_identifier_number, ''),
  major_classification = coalesce(major_classification, ''),
  sub_classification = coalesce(sub_classification, ''),
  advocacies = coalesce(advocacies, '{}'::text[]),
  profile_status = coalesce(profile_status, 'incomplete'::public.profile_status)
where
  is_existing_organization is null
  or organization_identifier_number is null
  or major_classification is null
  or sub_classification is null
  or advocacies is null
  or profile_status is null;

alter table if exists public.organization_profiles
  alter column is_existing_organization set default false,
  alter column organization_identifier_number set default '',
  alter column major_classification set default '',
  alter column sub_classification set default '',
  alter column advocacies set default '{}'::text[],
  alter column profile_status set default 'incomplete';

alter table if exists public.organization_profiles
  alter column is_existing_organization set not null,
  alter column organization_identifier_number set not null,
  alter column major_classification set not null,
  alter column sub_classification set not null,
  alter column advocacies set not null,
  alter column profile_status set not null;

create table if not exists public.required_document_types (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  description text not null default '',
  required_year integer,
  is_required boolean not null default true,
  template_url text,
  template_description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.document_submissions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organization_profiles(id) on delete cascade,
  submitted_by uuid not null references auth.users(id) on delete cascade,
  status public.document_submission_status not null default 'not_started',
  user_confirmed boolean not null default false,
  submitted_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  overall_remarks text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.document_submission_files (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null references public.document_submissions(id) on delete cascade,
  document_type_id uuid not null references public.required_document_types(id) on delete restrict,
  file_url text not null,
  file_name text not null,
  file_type text not null,
  file_size bigint not null default 0,
  ocr_text text,
  ocr_status public.ocr_status not null default 'pending',
  ocr_confidence numeric(5,2) not null default 0,
  validation_status public.document_file_validation_status not null default 'missing',
  admin_status public.document_submission_status not null default 'draft',
  admin_remarks text,
  ocr_metadata jsonb,
  uploaded_at timestamptz,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_document_submission_file unique (submission_id, document_type_id)
);

create table if not exists public.budget_requests (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organization_profiles(id) on delete cascade,
  submitted_by uuid not null references auth.users(id) on delete cascade,
  activity_title text not null,
  activity_description text not null default '',
  activity_date date not null,
  venue text not null,
  requested_amount numeric(14,2) not null default 0 check (requested_amount > 0),
  approved_amount numeric(14,2) not null default 0 check (approved_amount >= 0),
  released_amount numeric(14,2) not null default 0 check (released_amount >= 0),
  release_date date,
  purpose_category text not null default '',
  status public.budget_request_status not null default 'draft',
  remarks text,
  go_signal_at timestamptz,
  hard_copy_submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.budget_request_files (
  id uuid primary key default gen_random_uuid(),
  budget_request_id uuid not null references public.budget_requests(id) on delete cascade,
  file_url text not null,
  file_name text not null,
  file_type text not null,
  file_size bigint not null default 0,
  uploaded_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.liquidation_reports (
  id uuid primary key default gen_random_uuid(),
  budget_request_id uuid not null unique references public.budget_requests(id) on delete cascade,
  organization_id uuid not null references public.organization_profiles(id) on delete cascade,
  submitted_by uuid not null references auth.users(id) on delete cascade,
  status public.liquidation_report_status not null default 'pending_activity_completion',
  remarks text,
  go_signal_at timestamptz,
  deadline_at timestamptz,
  hard_copy_submitted_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.liquidation_report_files (
  id uuid primary key default gen_random_uuid(),
  liquidation_report_id uuid not null references public.liquidation_reports(id) on delete cascade,
  file_url text not null,
  file_name text not null,
  file_type text not null,
  file_size bigint not null default 0,
  uploaded_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.news_releases (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  facebook_post_url text not null,
  date_posted date not null,
  visibility_status public.visibility_status not null default 'draft',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transparency_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  category text not null,
  attachment_url text,
  visibility_status public.visibility_status not null default 'draft',
  post_date date not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.compliance_remarks (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organization_profiles(id) on delete cascade,
  related_type text not null,
  related_id uuid,
  remark_type text not null,
  consequence_type text not null,
  message text not null,
  status public.compliance_remark_status not null default 'open',
  created_by uuid references auth.users(id) on delete set null,
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  organization_id uuid references public.organization_profiles(id) on delete cascade,
  title text not null,
  message text not null,
  type public.notification_type not null,
  related_type text not null,
  related_id uuid,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id uuid primary key default gen_random_uuid(),
  actor_user_id uuid references auth.users(id) on delete set null,
  organization_id uuid references public.organization_profiles(id) on delete cascade,
  action text not null,
  related_type text not null,
  related_id uuid,
  description text not null,
  created_at timestamptz not null default now()
);

alter table if exists public.activity_logs
  alter column action type text using action::text;

-- Legacy compatibility tables kept intentionally so older pages and future migrations can be bridged without breaking the current app.
create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  type text not null,
  focus text not null default '',
  status text not null default 'active',
  source_post_url text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.programs (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  description text not null default '',
  status text not null default 'published',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  description text not null default '',
  status text not null default 'upcoming',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.disclosure_documents (
  id uuid primary key default gen_random_uuid(),
  doc_code text not null unique,
  title text not null,
  document_type text not null,
  fiscal_year integer,
  quarter text,
  published_date date,
  public_url text,
  storage_path text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================================
-- Indexes
-- ============================================================================

create index if not exists idx_user_roles_user_id on public.user_roles(user_id);
create index if not exists idx_admin_accounts_username on public.admin_accounts(username);
create index if not exists idx_admin_sessions_admin_id on public.admin_sessions(admin_id, expires_at desc);
create index if not exists idx_organization_profiles_barangay on public.organization_profiles(barangay);
create index if not exists idx_organization_profiles_status on public.organization_profiles(profile_status);
create index if not exists idx_required_document_types_sort_order on public.required_document_types(sort_order);
create index if not exists idx_document_submissions_org on public.document_submissions(organization_id, created_at desc);
create index if not exists idx_document_submissions_status on public.document_submissions(status);
create index if not exists idx_document_submission_files_submission on public.document_submission_files(submission_id);
create index if not exists idx_budget_requests_org on public.budget_requests(organization_id, created_at desc);
create index if not exists idx_budget_requests_status on public.budget_requests(status);
create index if not exists idx_budget_request_files_budget on public.budget_request_files(budget_request_id);
create index if not exists idx_liquidation_reports_budget on public.liquidation_reports(budget_request_id);
create index if not exists idx_liquidation_reports_status on public.liquidation_reports(status);
create index if not exists idx_liquidation_report_files_report on public.liquidation_report_files(liquidation_report_id);
create index if not exists idx_news_releases_visibility on public.news_releases(visibility_status, date_posted desc);
create index if not exists idx_transparency_posts_visibility on public.transparency_posts(visibility_status, post_date desc);
create index if not exists idx_compliance_remarks_org on public.compliance_remarks(organization_id, created_at desc);
create index if not exists idx_notifications_user_read on public.notifications(user_id, is_read, created_at desc);
create index if not exists idx_activity_logs_org on public.activity_logs(organization_id, created_at desc);

-- ============================================================================
-- Functions / Triggers
-- ============================================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.current_user_has_any_role(_roles public.app_role_code[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select case
    when auth.uid() is null then false
    else exists (
      select 1
      from public.user_roles ur
      join public.roles r on r.id = ur.role_id
      where ur.user_id = auth.uid()
        and r.code = any(_roles)
    )
  end;
$$;

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_user_has_any_role(array['admin']::public.app_role_code[]);
$$;

drop function if exists public.authenticate_admin_account(text, text);
create or replace function public.authenticate_admin_account(_username text, _password text)
returns table (
  admin_id uuid,
  username citext,
  email citext,
  display_name text,
  session_token text,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin public.admin_accounts%rowtype;
  _session_token text;
  _expires_at timestamptz;
begin
  select *
  into _admin
  from public.admin_accounts aa
  where aa.is_active = true
    and lower(aa.username::text) = lower(trim(_username))
    and aa.password_hash = extensions.crypt(_password, aa.password_hash)
  limit 1;

  if not found then
    return;
  end if;

  _session_token := encode(extensions.gen_random_bytes(32), 'hex');
  _expires_at := now() + interval '12 hours';

  insert into public.admin_sessions (
    admin_id,
    token_hash,
    expires_at
  )
  values (
    _admin.id,
    encode(extensions.digest(_session_token, 'sha256'), 'hex'),
    _expires_at
  );

  return query
  select
    _admin.id,
    _admin.username,
    _admin.email,
    _admin.display_name,
    _session_token,
    _expires_at;
end;
$$;

create or replace function public.validate_admin_session_token(_session_token text)
returns table (
  admin_id uuid,
  username citext,
  email citext,
  display_name text,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.admin_sessions
  set last_used_at = now()
  where token_hash = encode(extensions.digest(_session_token, 'sha256'), 'hex')
    and revoked_at is null
    and public.admin_sessions.expires_at > now();

  return query
  select
    aa.id,
    aa.username,
    aa.email,
    aa.display_name,
    s.expires_at
  from public.admin_sessions s
  join public.admin_accounts aa on aa.id = s.admin_id
  where s.token_hash = encode(extensions.digest(_session_token, 'sha256'), 'hex')
    and s.revoked_at is null
    and s.expires_at > now()
    and aa.is_active = true
  limit 1;
end;
$$;

create or replace function public.revoke_admin_session_token(_session_token text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.admin_sessions
  set revoked_at = now()
  where token_hash = encode(extensions.digest(_session_token, 'sha256'), 'hex')
    and revoked_at is null;
end;
$$;

create or replace function public.create_admin_template_document(
  _session_token text,
  _name text,
  _description text,
  _template_description text
)
returns table (
  id uuid,
  name text,
  description text,
  template_url text,
  template_description text,
  sort_order integer,
  is_required boolean,
  is_active boolean,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  _next_sort_order integer;
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  select coalesce(max(rdt.sort_order), 0) + 1
  into _next_sort_order
  from public.required_document_types rdt;

  return query
  insert into public.required_document_types (
    name,
    description,
    required_year,
    is_required,
    template_url,
    template_description,
    sort_order,
    is_active
  )
  values (
    trim(_name),
    coalesce(_description, ''),
    extract(year from now())::integer,
    true,
    '',
    coalesce(_template_description, ''),
    _next_sort_order,
    true
  )
  returning
    required_document_types.id,
    required_document_types.name,
    required_document_types.description,
    required_document_types.template_url,
    required_document_types.template_description,
    required_document_types.sort_order,
    required_document_types.is_required,
    required_document_types.is_active,
    required_document_types.updated_at;
end;
$$;

create or replace function public.update_admin_template_document(
  _session_token text,
  _template_id uuid,
  _name text,
  _description text,
  _template_description text
)
returns table (
  id uuid,
  name text,
  description text,
  template_url text,
  template_description text,
  sort_order integer,
  is_required boolean,
  is_active boolean,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  return query
  update public.required_document_types
  set
    name = trim(_name),
    description = coalesce(_description, ''),
    template_description = coalesce(_template_description, ''),
    updated_at = now()
  where required_document_types.id = _template_id
  returning
    required_document_types.id,
    required_document_types.name,
    required_document_types.description,
    required_document_types.template_url,
    required_document_types.template_description,
    required_document_types.sort_order,
    required_document_types.is_required,
    required_document_types.is_active,
    required_document_types.updated_at;
end;
$$;

create or replace function public.update_admin_template_file_url(
  _session_token text,
  _template_id uuid,
  _template_url text
)
returns table (
  id uuid,
  name text,
  description text,
  template_url text,
  template_description text,
  sort_order integer,
  is_required boolean,
  is_active boolean,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  return query
  update public.required_document_types
  set
    template_url = coalesce(_template_url, ''),
    updated_at = now()
  where required_document_types.id = _template_id
  returning
    required_document_types.id,
    required_document_types.name,
    required_document_types.description,
    required_document_types.template_url,
    required_document_types.template_description,
    required_document_types.sort_order,
    required_document_types.is_required,
    required_document_types.is_active,
    required_document_types.updated_at;
end;
$$;

create or replace function public.deactivate_admin_template_document(
  _session_token text,
  _template_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  update public.required_document_types
  set
    is_active = false,
    updated_at = now()
  where id = _template_id;
end;
$$;

create or replace function public.create_admin_news_release(
  _session_token text,
  _title text,
  _description text,
  _facebook_post_url text,
  _date_posted date,
  _visibility_status public.visibility_status
)
returns table (
  id uuid,
  title text,
  description text,
  facebook_post_url text,
  date_posted date,
  visibility_status public.visibility_status,
  created_by uuid,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  return query
  insert into public.news_releases (
    title,
    description,
    facebook_post_url,
    date_posted,
    visibility_status,
    created_by
  )
  values (
    trim(_title),
    coalesce(_description, ''),
    trim(_facebook_post_url),
    _date_posted,
    coalesce(_visibility_status, 'draft'::public.visibility_status),
    null
  )
  returning
    news_releases.id,
    news_releases.title,
    news_releases.description,
    news_releases.facebook_post_url,
    news_releases.date_posted,
    news_releases.visibility_status,
    news_releases.created_by,
    news_releases.created_at,
    news_releases.updated_at;
end;
$$;

create or replace function public.update_admin_news_release(
  _session_token text,
  _news_release_id uuid,
  _title text,
  _description text,
  _facebook_post_url text,
  _date_posted date,
  _visibility_status public.visibility_status
)
returns table (
  id uuid,
  title text,
  description text,
  facebook_post_url text,
  date_posted date,
  visibility_status public.visibility_status,
  created_by uuid,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  return query
  update public.news_releases
  set
    title = coalesce(trim(_title), news_releases.title),
    description = coalesce(_description, news_releases.description),
    facebook_post_url = coalesce(trim(_facebook_post_url), news_releases.facebook_post_url),
    date_posted = coalesce(_date_posted, news_releases.date_posted),
    visibility_status = coalesce(_visibility_status, news_releases.visibility_status),
    updated_at = now()
  where news_releases.id = _news_release_id
  returning
    news_releases.id,
    news_releases.title,
    news_releases.description,
    news_releases.facebook_post_url,
    news_releases.date_posted,
    news_releases.visibility_status,
    news_releases.created_by,
    news_releases.created_at,
    news_releases.updated_at;
end;
$$;

create or replace function public.delete_admin_news_release(
  _session_token text,
  _news_release_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  delete from public.news_releases
  where id = _news_release_id;
end;
$$;

create or replace function public.create_admin_transparency_post(
  _session_token text,
  _title text,
  _description text,
  _category text,
  _attachment_url text,
  _post_date date,
  _visibility_status public.visibility_status
)
returns table (
  id uuid,
  title text,
  description text,
  category text,
  attachment_url text,
  visibility_status public.visibility_status,
  post_date date,
  created_by uuid,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  return query
  insert into public.transparency_posts (
    title,
    description,
    category,
    attachment_url,
    visibility_status,
    post_date,
    created_by
  )
  values (
    trim(_title),
    coalesce(_description, ''),
    trim(_category),
    nullif(trim(coalesce(_attachment_url, '')), ''),
    coalesce(_visibility_status, 'draft'::public.visibility_status),
    _post_date,
    null
  )
  returning
    transparency_posts.id,
    transparency_posts.title,
    transparency_posts.description,
    transparency_posts.category,
    transparency_posts.attachment_url,
    transparency_posts.visibility_status,
    transparency_posts.post_date,
    transparency_posts.created_by,
    transparency_posts.created_at,
    transparency_posts.updated_at;
end;
$$;

create or replace function public.update_admin_transparency_post(
  _session_token text,
  _post_id uuid,
  _title text,
  _description text,
  _category text,
  _attachment_url text,
  _post_date date,
  _visibility_status public.visibility_status
)
returns table (
  id uuid,
  title text,
  description text,
  category text,
  attachment_url text,
  visibility_status public.visibility_status,
  post_date date,
  created_by uuid,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  return query
  update public.transparency_posts
  set
    title = coalesce(trim(_title), transparency_posts.title),
    description = coalesce(_description, transparency_posts.description),
    category = coalesce(trim(_category), transparency_posts.category),
    attachment_url = case
      when _attachment_url is null then transparency_posts.attachment_url
      else nullif(trim(_attachment_url), '')
    end,
    post_date = coalesce(_post_date, transparency_posts.post_date),
    visibility_status = coalesce(_visibility_status, transparency_posts.visibility_status),
    updated_at = now()
  where transparency_posts.id = _post_id
  returning
    transparency_posts.id,
    transparency_posts.title,
    transparency_posts.description,
    transparency_posts.category,
    transparency_posts.attachment_url,
    transparency_posts.visibility_status,
    transparency_posts.post_date,
    transparency_posts.created_by,
    transparency_posts.created_at,
    transparency_posts.updated_at;
end;
$$;

create or replace function public.delete_admin_transparency_post(
  _session_token text,
  _post_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  delete from public.transparency_posts
  where id = _post_id;
end;
$$;

create or replace function public.create_admin_activity_log(
  _session_token text,
  _organization_id uuid,
  _action text,
  _related_type text,
  _related_id uuid,
  _description text
)
returns table (
  id uuid,
  actor_user_id uuid,
  organization_id uuid,
  action text,
  related_type text,
  related_id uuid,
  description text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  return query
  insert into public.activity_logs (
    actor_user_id,
    organization_id,
    action,
    related_type,
    related_id,
    description
  )
  values (
    null,
    _organization_id,
    trim(_action),
    trim(_related_type),
    _related_id,
    _description
  )
  returning
    activity_logs.id,
    activity_logs.actor_user_id,
    activity_logs.organization_id,
    activity_logs.action,
    activity_logs.related_type,
    activity_logs.related_id,
    activity_logs.description,
    activity_logs.created_at;
end;
$$;

drop function if exists public.update_admin_organization_profile_review(text, uuid, public.profile_status, timestamptz);
create or replace function public.update_admin_organization_profile_review(
  _session_token text,
  _organization_profile_id uuid,
  _profile_status public.profile_status,
  _verified_at timestamptz default null
)
returns table (
  id uuid,
  user_id uuid,
  organization_name text,
  organization_email citext,
  contact_number text,
  district text,
  barangay text,
  is_existing_organization boolean,
  organization_identifier_number text,
  major_classification text,
  sub_classification text,
  advocacies text[],
  adviser_name text,
  representative_name text,
  address text,
  facebook_page_url text,
  profile_status public.profile_status,
  verified_at timestamptz,
  internal_notes text,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  return query
  update public.organization_profiles
  set
    profile_status = _profile_status,
    verified_at = case
      when _profile_status = 'verified'::public.profile_status then coalesce(_verified_at, now())
      else null
    end,
    updated_at = now()
  where organization_profiles.id = _organization_profile_id
  returning
    organization_profiles.id,
    organization_profiles.user_id,
    organization_profiles.organization_name,
    organization_profiles.organization_email,
    organization_profiles.contact_number,
    organization_profiles.district,
    organization_profiles.barangay,
    organization_profiles.is_existing_organization,
    organization_profiles.organization_identifier_number,
    organization_profiles.major_classification,
    organization_profiles.sub_classification,
    organization_profiles.advocacies,
    organization_profiles.adviser_name,
    organization_profiles.representative_name,
    organization_profiles.address,
    organization_profiles.facebook_page_url,
    organization_profiles.profile_status,
    organization_profiles.verified_at,
    organization_profiles.internal_notes,
    organization_profiles.created_at,
    organization_profiles.updated_at;
end;
$$;

create or replace function public.update_admin_document_submission_review(
  _session_token text,
  _submission_id uuid,
  _status public.document_submission_status,
  _overall_remarks text default null,
  _admin_remarks text default null
)
returns table (
  id uuid,
  organization_id uuid,
  submitted_by uuid,
  status public.document_submission_status,
  user_confirmed boolean,
  submitted_at timestamptz,
  reviewed_by uuid,
  reviewed_at timestamptz,
  overall_remarks text,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
  _reviewed_at timestamptz := now();
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  update public.document_submission_files
  set
    admin_status = _status,
    admin_remarks = coalesce(_admin_remarks, document_submission_files.admin_remarks),
    reviewed_at = _reviewed_at,
    updated_at = _reviewed_at
  where submission_id = _submission_id;

  return query
  update public.document_submissions
  set
    status = _status,
    reviewed_by = null,
    reviewed_at = _reviewed_at,
    overall_remarks = coalesce(_overall_remarks, document_submissions.overall_remarks),
    updated_at = _reviewed_at
  where document_submissions.id = _submission_id
  returning
    document_submissions.id,
    document_submissions.organization_id,
    document_submissions.submitted_by,
    document_submissions.status,
    document_submissions.user_confirmed,
    document_submissions.submitted_at,
    document_submissions.reviewed_by,
    document_submissions.reviewed_at,
    document_submissions.overall_remarks,
    document_submissions.created_at,
    document_submissions.updated_at;
end;
$$;

create or replace function public.update_admin_document_submission_file_review(
  _session_token text,
  _file_id uuid,
  _status public.document_submission_status,
  _admin_remarks text default null
)
returns setof public.document_submission_files
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
  _reviewed_at timestamptz := now();
  _submission_id uuid;
  _document_name text;
  _overall_status public.document_submission_status;
  _overall_remarks text;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  select
    document_submission_files.submission_id,
    coalesce(required_document_types.name, document_submission_files.file_name)
  into _submission_id, _document_name
  from public.document_submission_files
  left join public.required_document_types
    on required_document_types.id = document_submission_files.document_type_id
  where document_submission_files.id = _file_id
  limit 1;

  if _submission_id is null then
    raise exception 'Document submission file was not found.';
  end if;

  update public.document_submission_files
  set
    admin_status = _status,
    admin_remarks = coalesce(_admin_remarks, document_submission_files.admin_remarks),
    reviewed_at = _reviewed_at,
    updated_at = _reviewed_at
  where document_submission_files.id = _file_id;

  select
    case
      when exists (
        select 1
        from public.document_submission_files
        where submission_id = _submission_id
          and admin_status = 'rejected_red'
      ) then 'rejected_red'::public.document_submission_status
      when exists (
        select 1
        from public.document_submission_files
        where submission_id = _submission_id
          and admin_status = 'needs_revision'
      ) then 'needs_revision'::public.document_submission_status
      when exists (
        select 1
        from public.document_submission_files
        where submission_id = _submission_id
      ) and not exists (
        select 1
        from public.document_submission_files
        where submission_id = _submission_id
          and admin_status <> 'approved_green'
      ) then 'approved_green'::public.document_submission_status
      else 'under_admin_review'::public.document_submission_status
    end
  into _overall_status;

  _overall_remarks :=
    case
      when _status = 'approved_green' then format('Admin approved %s.', _document_name)
      when _status = 'needs_revision' then format('Admin requested revisions for %s.', _document_name)
      else format('Admin rejected %s.', _document_name)
    end;

  update public.document_submissions
  set
    status = _overall_status,
    reviewed_by = null,
    reviewed_at = _reviewed_at,
    overall_remarks = _overall_remarks,
    updated_at = _reviewed_at
  where document_submissions.id = _submission_id;

  return query
  select *
  from public.document_submission_files
  where document_submission_files.id = _file_id;
end;
$$;

create or replace function public.update_admin_budget_request(
  _session_token text,
  _budget_request_id uuid,
  _status public.budget_request_status default null,
  _approved_amount numeric(14,2) default null,
  _released_amount numeric(14,2) default null,
  _release_date date default null,
  _remarks text default null,
  _go_signal_at timestamptz default null,
  _hard_copy_submitted_at timestamptz default null
)
returns table (
  id uuid,
  organization_id uuid,
  submitted_by uuid,
  activity_title text,
  activity_description text,
  activity_date date,
  venue text,
  requested_amount numeric(14,2),
  approved_amount numeric(14,2),
  released_amount numeric(14,2),
  release_date date,
  purpose_category text,
  status public.budget_request_status,
  remarks text,
  go_signal_at timestamptz,
  hard_copy_submitted_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  return query
  update public.budget_requests
  set
    status = coalesce(_status, budget_requests.status),
    approved_amount = coalesce(_approved_amount, budget_requests.approved_amount),
    released_amount = coalesce(_released_amount, budget_requests.released_amount),
    release_date = coalesce(_release_date, budget_requests.release_date),
    remarks = coalesce(_remarks, budget_requests.remarks),
    go_signal_at = coalesce(_go_signal_at, budget_requests.go_signal_at),
    hard_copy_submitted_at = coalesce(_hard_copy_submitted_at, budget_requests.hard_copy_submitted_at),
    updated_at = now()
  where budget_requests.id = _budget_request_id
  returning
    budget_requests.id,
    budget_requests.organization_id,
    budget_requests.submitted_by,
    budget_requests.activity_title,
    budget_requests.activity_description,
    budget_requests.activity_date,
    budget_requests.venue,
    budget_requests.requested_amount,
    budget_requests.approved_amount,
    budget_requests.released_amount,
    budget_requests.release_date,
    budget_requests.purpose_category,
    budget_requests.status,
    budget_requests.remarks,
    budget_requests.go_signal_at,
    budget_requests.hard_copy_submitted_at,
    budget_requests.created_at,
    budget_requests.updated_at;
end;
$$;

create or replace function public.update_admin_liquidation_report(
  _session_token text,
  _liquidation_report_id uuid,
  _status public.liquidation_report_status default null,
  _remarks text default null,
  _go_signal_at timestamptz default null,
  _deadline_at timestamptz default null,
  _hard_copy_submitted_at timestamptz default null,
  _completed_at timestamptz default null
)
returns table (
  id uuid,
  budget_request_id uuid,
  organization_id uuid,
  submitted_by uuid,
  status public.liquidation_report_status,
  remarks text,
  go_signal_at timestamptz,
  deadline_at timestamptz,
  hard_copy_submitted_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  return query
  update public.liquidation_reports
  set
    status = coalesce(_status, liquidation_reports.status),
    remarks = coalesce(_remarks, liquidation_reports.remarks),
    go_signal_at = coalesce(_go_signal_at, liquidation_reports.go_signal_at),
    deadline_at = coalesce(_deadline_at, liquidation_reports.deadline_at),
    hard_copy_submitted_at = coalesce(_hard_copy_submitted_at, liquidation_reports.hard_copy_submitted_at),
    completed_at = coalesce(_completed_at, liquidation_reports.completed_at),
    updated_at = now()
  where liquidation_reports.id = _liquidation_report_id
  returning
    liquidation_reports.id,
    liquidation_reports.budget_request_id,
    liquidation_reports.organization_id,
    liquidation_reports.submitted_by,
    liquidation_reports.status,
    liquidation_reports.remarks,
    liquidation_reports.go_signal_at,
    liquidation_reports.deadline_at,
    liquidation_reports.hard_copy_submitted_at,
    liquidation_reports.completed_at,
    liquidation_reports.created_at,
    liquidation_reports.updated_at;
end;
$$;

create or replace function public.get_admin_portal_snapshot(_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  _admin_id uuid;
begin
  select vat.admin_id
  into _admin_id
  from public.validate_admin_session_token(_session_token) vat
  limit 1;

  if _admin_id is null then
    raise exception 'Admin account is not authorized.';
  end if;

  return jsonb_build_object(
    'organization_profiles',
    coalesce(
      (
        select jsonb_agg(to_jsonb(op) order by op.created_at desc)
        from public.organization_profiles op
      ),
      '[]'::jsonb
    ),
    'document_submissions',
    coalesce(
      (
        select jsonb_agg(to_jsonb(ds) order by ds.created_at desc)
        from public.document_submissions ds
      ),
      '[]'::jsonb
    ),
    'document_submission_files',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', dsf.id,
            'submission_id', dsf.submission_id,
            'file_url', dsf.file_url,
            'file_name', dsf.file_name,
            'file_type', dsf.file_type,
            'file_size', dsf.file_size,
            'ocr_text', dsf.ocr_text,
            'ocr_status', dsf.ocr_status,
            'ocr_confidence', dsf.ocr_confidence,
            'validation_status', dsf.validation_status,
            'admin_status', dsf.admin_status,
            'admin_remarks', dsf.admin_remarks,
            'ocr_metadata', dsf.ocr_metadata,
            'uploaded_at', dsf.uploaded_at,
            'reviewed_at', dsf.reviewed_at,
            'created_at', dsf.created_at,
            'updated_at', dsf.updated_at,
            'required_document_types', jsonb_build_object('id', rdt.id, 'name', rdt.name)
          )
          order by dsf.created_at desc
        )
        from public.document_submission_files dsf
        left join public.required_document_types rdt on rdt.id = dsf.document_type_id
      ),
      '[]'::jsonb
    ),
    'budget_requests',
    coalesce(
      (
        select jsonb_agg(to_jsonb(br) order by br.created_at desc)
        from public.budget_requests br
      ),
      '[]'::jsonb
    ),
    'budget_request_files',
    coalesce(
      (
        select jsonb_agg(to_jsonb(brf) order by brf.created_at desc)
        from public.budget_request_files brf
      ),
      '[]'::jsonb
    ),
    'liquidation_reports',
    coalesce(
      (
        select jsonb_agg(to_jsonb(lr) order by lr.created_at desc)
        from public.liquidation_reports lr
      ),
      '[]'::jsonb
    ),
    'liquidation_report_files',
    coalesce(
      (
        select jsonb_agg(to_jsonb(lrf) order by lrf.created_at desc)
        from public.liquidation_report_files lrf
      ),
      '[]'::jsonb
    ),
    'news_releases',
    coalesce(
      (
        select jsonb_agg(to_jsonb(nr) order by nr.date_posted desc, nr.created_at desc)
        from public.news_releases nr
      ),
      '[]'::jsonb
    ),
    'transparency_posts',
    coalesce(
      (
        select jsonb_agg(to_jsonb(tp) order by tp.post_date desc, tp.created_at desc)
        from public.transparency_posts tp
      ),
      '[]'::jsonb
    ),
    'compliance_remarks',
    coalesce(
      (
        select jsonb_agg(to_jsonb(cr) order by cr.created_at desc)
        from public.compliance_remarks cr
      ),
      '[]'::jsonb
    ),
    'notifications',
    coalesce(
      (
        select jsonb_agg(to_jsonb(n) order by n.created_at desc)
        from public.notifications n
      ),
      '[]'::jsonb
    ),
    'activity_logs',
    coalesce(
      (
        select jsonb_agg(to_jsonb(al) order by al.created_at desc)
        from public.activity_logs al
      ),
      '[]'::jsonb
    ),
    'templates',
    coalesce(
      (
        select jsonb_agg(to_jsonb(rdt) order by rdt.sort_order asc)
        from public.required_document_types rdt
        where rdt.is_active = true
      ),
      '[]'::jsonb
    )
  );
end;
$$;

create or replace function public.ensure_liquidation_report_for_budget()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status in ('budget_released', 'completed') then
    insert into public.liquidation_reports (
      budget_request_id,
      organization_id,
      submitted_by,
      status,
      go_signal_at,
      deadline_at,
      created_at,
      updated_at
    )
    values (
      new.id,
      new.organization_id,
      new.submitted_by,
      'pending_activity_completion',
      coalesce(new.go_signal_at, now()),
      coalesce(new.go_signal_at, now()) + interval '1 month',
      now(),
      now()
    )
    on conflict (budget_request_id) do update
      set organization_id = excluded.organization_id,
          submitted_by = excluded.submitted_by,
          go_signal_at = coalesce(excluded.go_signal_at, public.liquidation_reports.go_signal_at),
          deadline_at = coalesce(excluded.deadline_at, public.liquidation_reports.deadline_at),
          updated_at = now();
  end if;
  return new;
end;
$$;

create or replace function public.notify_submission_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  org_user_id uuid;
  notif_type public.notification_type;
  notif_title text;
  notif_message text;
begin
  select op.user_id into org_user_id
  from public.organization_profiles op
  where op.id = new.organization_id;

  if org_user_id is null then
    return new;
  end if;

  if new.status = 'needs_revision' then
    notif_type := 'document_revision';
    notif_title := 'Document revision requested';
    notif_message := 'Admin requested corrections for your document submission.';
  elsif new.status = 'approved_green' then
    notif_type := 'document_green';
    notif_title := 'Document submission approved';
    notif_message := 'Your document has been marked approved.';
  elsif new.status = 'rejected_red' then
    notif_type := 'document_red';
    notif_title := 'Document submission rejected';
    notif_message := 'Your document has been marked rejected.';
  else
    return new;
  end if;

  insert into public.notifications (user_id, organization_id, title, message, type, related_type, related_id)
  values (org_user_id, new.organization_id, notif_title, notif_message, notif_type, 'document_submission', new.id);

  insert into public.activity_logs (actor_user_id, organization_id, action, related_type, related_id, description)
  values (coalesce(new.reviewed_by, auth.uid()), new.organization_id, 'reviewed_documents', 'document_submission', new.id, notif_message);

  return new;
end;
$$;

create or replace function public.notify_organization_profile_review_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.profile_status is not distinct from new.profile_status then
    return new;
  end if;

  if new.profile_status = 'verified' then
    insert into public.notifications (user_id, organization_id, title, message, type, related_type, related_id)
    values (
      new.user_id,
      new.id,
      'Registration verified',
      'The admin verified your organization registration.',
      'completed',
      'organization_profile',
      new.id
    );
  elsif new.profile_status = 'needs_update' then
    insert into public.notifications (user_id, organization_id, title, message, type, related_type, related_id)
    values (
      new.user_id,
      new.id,
      'Registration needs update',
      'The admin reviewed your organization profile and requested updates before verification.',
      'document_revision',
      'organization_profile',
      new.id
    );
  end if;

  return new;
end;
$$;

create or replace function public.notify_budget_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  org_user_id uuid;
  notif_type public.notification_type;
  notif_title text;
  notif_message text;
begin
  select op.user_id into org_user_id
  from public.organization_profiles op
  where op.id = new.organization_id;

  if new.status in ('approved_for_ftf_green', 'budget_released') then
    notif_type := case when new.status = 'budget_released' then 'budget_released' else 'budget_go_signal' end;
    notif_title := case when new.status = 'budget_released' then 'Budget released' else 'Budget go signal issued' end;
    notif_message := case
      when new.status = 'budget_released' then 'Your budget has been released.'
      else 'Your soft copy requirements have been pre-checked. You may now submit the hard copies face-to-face.'
    end;

    insert into public.notifications (user_id, organization_id, title, message, type, related_type, related_id)
    values (org_user_id, new.organization_id, notif_title, notif_message, notif_type, 'budget_request', new.id);
  elsif new.status = 'needs_revision' then
    insert into public.notifications (user_id, organization_id, title, message, type, related_type, related_id)
    values (org_user_id, new.organization_id, 'Budget revision requested', 'Admin requested corrections for your budget request.', 'budget_revision', 'budget_request', new.id);
  elsif new.status = 'rejected_red' then
    insert into public.notifications (user_id, organization_id, title, message, type, related_type, related_id)
    values (org_user_id, new.organization_id, 'Budget request rejected', 'Your budget request was marked red.', 'document_red', 'budget_request', new.id);
  end if;

  insert into public.activity_logs (actor_user_id, organization_id, action, related_type, related_id, description)
  values (coalesce(auth.uid(), new.submitted_by), new.organization_id, 'reviewed_budget_request', 'budget_request', new.id, coalesce(new.remarks, 'Budget request status changed.'));

  return new;
end;
$$;

create or replace function public.notify_liquidation_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  org_user_id uuid;
begin
  select op.user_id into org_user_id
  from public.organization_profiles op
  where op.id = new.organization_id;

  if new.status = 'approved_for_ftf_green' then
    if new.go_signal_at is not null then
      new.deadline_at := new.go_signal_at + interval '1 month';
    end if;
    insert into public.notifications (user_id, organization_id, title, message, type, related_type, related_id)
    values (org_user_id, new.organization_id, 'Liquidation go signal issued', 'Your liquidation soft copies have been pre-checked. You may now submit the hard copies face-to-face.', 'liquidation_go_signal', 'liquidation_report', new.id);
  elsif new.status = 'needs_revision' then
    insert into public.notifications (user_id, organization_id, title, message, type, related_type, related_id)
    values (org_user_id, new.organization_id, 'Liquidation revision requested', 'Admin requested corrections for your liquidation report.', 'liquidation_revision', 'liquidation_report', new.id);
  elsif new.status = 'overdue' then
    insert into public.notifications (user_id, organization_id, title, message, type, related_type, related_id)
    values (org_user_id, new.organization_id, 'Liquidation overdue', 'Your liquidation submission is overdue.', 'overdue', 'liquidation_report', new.id);
  elsif new.status = 'completed_liquidated' then
    new.completed_at := now();
    insert into public.notifications (user_id, organization_id, title, message, type, related_type, related_id)
    values (org_user_id, new.organization_id, 'Liquidation completed', 'Your liquidation record has been completed.', 'completed', 'liquidation_report', new.id);
  end if;

  insert into public.activity_logs (actor_user_id, organization_id, action, related_type, related_id, description)
  values (coalesce(auth.uid(), new.submitted_by), new.organization_id, 'reviewed_liquidation_report', 'liquidation_report', new.id, coalesce(new.remarks, 'Liquidation status updated.'));

  return new;
end;
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  default_role_id smallint;
begin
  insert into public.user_profiles (user_id, email, full_name, display_name)
  values (
    new.id,
    coalesce(new.email, new.id::text || '@local.invalid'),
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'display_name', '')
  )
  on conflict (user_id) do update
    set email = excluded.email,
        full_name = excluded.full_name,
        display_name = excluded.display_name,
        updated_at = now();

  select id into default_role_id from public.roles where code = 'youth' limit 1;
  if default_role_id is not null then
    insert into public.user_roles (user_id, role_id) values (new.id, default_role_id)
    on conflict (user_id, role_id) do nothing;
  end if;

  return new;
end;
$$;

-- Triggers
drop trigger if exists trg_user_profiles_updated_at on public.user_profiles;
create trigger trg_user_profiles_updated_at before update on public.user_profiles for each row execute function public.set_updated_at();

drop trigger if exists trg_admin_accounts_updated_at on public.admin_accounts;
create trigger trg_admin_accounts_updated_at before update on public.admin_accounts for each row execute function public.set_updated_at();

drop trigger if exists trg_policy_versions_updated_at on public.policy_versions;
create trigger trg_policy_versions_updated_at before update on public.policy_versions for each row execute function public.set_updated_at();

drop trigger if exists trg_organization_profiles_updated_at on public.organization_profiles;
create trigger trg_organization_profiles_updated_at before update on public.organization_profiles for each row execute function public.set_updated_at();

drop trigger if exists trg_required_document_types_updated_at on public.required_document_types;
create trigger trg_required_document_types_updated_at before update on public.required_document_types for each row execute function public.set_updated_at();

drop trigger if exists trg_document_submissions_updated_at on public.document_submissions;
create trigger trg_document_submissions_updated_at before update on public.document_submissions for each row execute function public.set_updated_at();

drop trigger if exists trg_document_submission_files_updated_at on public.document_submission_files;
create trigger trg_document_submission_files_updated_at before update on public.document_submission_files for each row execute function public.set_updated_at();

drop trigger if exists trg_budget_requests_updated_at on public.budget_requests;
create trigger trg_budget_requests_updated_at before update on public.budget_requests for each row execute function public.set_updated_at();

drop trigger if exists trg_budget_request_status_sync on public.budget_requests;
create trigger trg_budget_request_status_sync after insert or update on public.budget_requests for each row execute function public.ensure_liquidation_report_for_budget();

drop trigger if exists trg_liquidation_reports_updated_at on public.liquidation_reports;
create trigger trg_liquidation_reports_updated_at before update on public.liquidation_reports for each row execute function public.set_updated_at();

drop trigger if exists trg_liquidation_report_status_sync on public.liquidation_reports;
create trigger trg_liquidation_report_status_sync before insert or update on public.liquidation_reports for each row execute function public.notify_liquidation_change();

drop trigger if exists trg_document_submission_notify on public.document_submissions;
create trigger trg_document_submission_notify after update on public.document_submissions for each row when (old.status is distinct from new.status) execute function public.notify_submission_change();

drop trigger if exists trg_organization_profile_review_notify on public.organization_profiles;
create trigger trg_organization_profile_review_notify after update on public.organization_profiles for each row when (old.profile_status is distinct from new.profile_status) execute function public.notify_organization_profile_review_change();

drop trigger if exists trg_budget_request_notify on public.budget_requests;
create trigger trg_budget_request_notify after update on public.budget_requests for each row when (old.status is distinct from new.status) execute function public.notify_budget_change();

drop trigger if exists trg_news_releases_updated_at on public.news_releases;
create trigger trg_news_releases_updated_at before update on public.news_releases for each row execute function public.set_updated_at();

drop trigger if exists trg_transparency_posts_updated_at on public.transparency_posts;
create trigger trg_transparency_posts_updated_at before update on public.transparency_posts for each row execute function public.set_updated_at();

drop trigger if exists trg_compliance_remarks_updated_at on public.compliance_remarks;
create trigger trg_compliance_remarks_updated_at before update on public.compliance_remarks for each row execute function public.set_updated_at();

drop trigger if exists trg_auth_user_created on auth.users;
create trigger trg_auth_user_created after insert on auth.users for each row execute function public.handle_new_auth_user();

-- ============================================================================
-- RLS Policies
-- ============================================================================

alter table public.roles enable row level security;
alter table public.user_roles enable row level security;
alter table public.user_profiles enable row level security;
alter table public.admin_accounts enable row level security;
alter table public.admin_sessions enable row level security;
alter table public.policy_versions enable row level security;
alter table public.user_policy_acceptance enable row level security;
alter table public.barangays enable row level security;
alter table public.organization_profiles enable row level security;
alter table public.required_document_types enable row level security;
alter table public.document_submissions enable row level security;
alter table public.document_submission_files enable row level security;
alter table public.budget_requests enable row level security;
alter table public.budget_request_files enable row level security;
alter table public.liquidation_reports enable row level security;
alter table public.liquidation_report_files enable row level security;
alter table public.news_releases enable row level security;
alter table public.transparency_posts enable row level security;
alter table public.compliance_remarks enable row level security;
alter table public.notifications enable row level security;
alter table public.activity_logs enable row level security;
alter table public.organizations enable row level security;
alter table public.programs enable row level security;
alter table public.events enable row level security;
alter table public.disclosure_documents enable row level security;

-- Roles and profiles
drop policy if exists admin_manage_roles on public.roles;
create policy admin_manage_roles on public.roles
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists user_roles_read_admin on public.user_roles;
create policy user_roles_read_admin on public.user_roles
for select using (public.current_user_is_admin() or auth.uid() = user_id);

drop policy if exists user_roles_manage_admin on public.user_roles;
create policy user_roles_manage_admin on public.user_roles
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists user_profiles_self_or_admin on public.user_profiles;
create policy user_profiles_self_or_admin on public.user_profiles
for all using (public.current_user_is_admin() or auth.uid() = user_id) with check (public.current_user_is_admin() or auth.uid() = user_id);

drop policy if exists admin_accounts_admin_manage on public.admin_accounts;
create policy admin_accounts_admin_manage on public.admin_accounts
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists admin_sessions_admin_manage on public.admin_sessions;
create policy admin_sessions_admin_manage on public.admin_sessions
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists active_policy_versions_read on public.policy_versions;
create policy active_policy_versions_read on public.policy_versions
for select using (is_active = true or public.current_user_is_admin());

drop policy if exists policy_versions_manage_admin on public.policy_versions;
create policy policy_versions_manage_admin on public.policy_versions
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists user_policy_acceptance_self_or_admin on public.user_policy_acceptance;
create policy user_policy_acceptance_self_or_admin on public.user_policy_acceptance
for all using (auth.uid() = user_id or public.current_user_is_admin()) with check (auth.uid() = user_id or public.current_user_is_admin());

drop policy if exists barangays_public_read on public.barangays;
create policy barangays_public_read on public.barangays
for select using (true);

drop policy if exists barangays_admin_manage on public.barangays;
create policy barangays_admin_manage on public.barangays
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

-- Organization workflow
drop policy if exists organization_profiles_self_or_admin on public.organization_profiles;
create policy organization_profiles_self_or_admin on public.organization_profiles
for all using (public.current_user_is_admin() or auth.uid() = user_id) with check (public.current_user_is_admin() or auth.uid() = user_id);

drop policy if exists required_document_types_read on public.required_document_types;
create policy required_document_types_read on public.required_document_types
for select using (true);

drop policy if exists required_document_types_admin_manage on public.required_document_types;
create policy required_document_types_admin_manage on public.required_document_types
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists document_submissions_self_or_admin on public.document_submissions;
create policy document_submissions_self_or_admin on public.document_submissions
for all using (
  public.current_user_is_admin()
  or submitted_by = auth.uid()
  or exists (
    select 1 from public.organization_profiles op
    where op.id = document_submissions.organization_id and op.user_id = auth.uid()
  )
) with check (
  public.current_user_is_admin()
  or submitted_by = auth.uid()
  or exists (
    select 1 from public.organization_profiles op
    where op.id = document_submissions.organization_id and op.user_id = auth.uid()
  )
);

drop policy if exists document_submission_files_self_or_admin on public.document_submission_files;
create policy document_submission_files_self_or_admin on public.document_submission_files
for all using (
  public.current_user_is_admin()
  or exists (
    select 1
    from public.document_submissions ds
    join public.organization_profiles op on op.id = ds.organization_id
    where ds.id = document_submission_files.submission_id
      and (op.user_id = auth.uid() or ds.submitted_by = auth.uid())
  )
) with check (
  public.current_user_is_admin()
  or exists (
    select 1
    from public.document_submissions ds
    join public.organization_profiles op on op.id = ds.organization_id
    where ds.id = document_submission_files.submission_id
      and (op.user_id = auth.uid() or ds.submitted_by = auth.uid())
  )
);

drop policy if exists budget_requests_self_or_admin on public.budget_requests;
create policy budget_requests_self_or_admin on public.budget_requests
for all using (
  public.current_user_is_admin()
  or submitted_by = auth.uid()
  or exists (
    select 1 from public.organization_profiles op
    where op.id = budget_requests.organization_id and op.user_id = auth.uid()
  )
) with check (
  public.current_user_is_admin()
  or submitted_by = auth.uid()
  or exists (
    select 1 from public.organization_profiles op
    where op.id = budget_requests.organization_id and op.user_id = auth.uid()
  )
);

drop policy if exists budget_request_files_self_or_admin on public.budget_request_files;
create policy budget_request_files_self_or_admin on public.budget_request_files
for all using (
  public.current_user_is_admin()
  or exists (
    select 1
    from public.budget_requests br
    join public.organization_profiles op on op.id = br.organization_id
    where br.id = budget_request_files.budget_request_id
      and (op.user_id = auth.uid() or br.submitted_by = auth.uid())
  )
) with check (
  public.current_user_is_admin()
  or exists (
    select 1
    from public.budget_requests br
    join public.organization_profiles op on op.id = br.organization_id
    where br.id = budget_request_files.budget_request_id
      and (op.user_id = auth.uid() or br.submitted_by = auth.uid())
  )
);

drop policy if exists liquidation_reports_self_or_admin on public.liquidation_reports;
create policy liquidation_reports_self_or_admin on public.liquidation_reports
for all using (
  public.current_user_is_admin()
  or submitted_by = auth.uid()
  or exists (
    select 1 from public.organization_profiles op
    where op.id = liquidation_reports.organization_id and op.user_id = auth.uid()
  )
) with check (
  public.current_user_is_admin()
  or submitted_by = auth.uid()
  or exists (
    select 1 from public.organization_profiles op
    where op.id = liquidation_reports.organization_id and op.user_id = auth.uid()
  )
);

drop policy if exists liquidation_report_files_self_or_admin on public.liquidation_report_files;
create policy liquidation_report_files_self_or_admin on public.liquidation_report_files
for all using (
  public.current_user_is_admin()
  or exists (
    select 1
    from public.liquidation_reports lr
    join public.organization_profiles op on op.id = lr.organization_id
    where lr.id = liquidation_report_files.liquidation_report_id
      and (op.user_id = auth.uid() or lr.submitted_by = auth.uid())
  )
) with check (
  public.current_user_is_admin()
  or exists (
    select 1
    from public.liquidation_reports lr
    join public.organization_profiles op on op.id = lr.organization_id
    where lr.id = liquidation_report_files.liquidation_report_id
      and (op.user_id = auth.uid() or lr.submitted_by = auth.uid())
  )
);

drop policy if exists news_releases_read_published on public.news_releases;
create policy news_releases_read_published on public.news_releases
for select using (visibility_status = 'published' or public.current_user_is_admin());

drop policy if exists news_releases_admin_manage on public.news_releases;
create policy news_releases_admin_manage on public.news_releases
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists transparency_posts_read_published on public.transparency_posts;
create policy transparency_posts_read_published on public.transparency_posts
for select using (visibility_status = 'published' or public.current_user_is_admin());

drop policy if exists transparency_posts_admin_manage on public.transparency_posts;
create policy transparency_posts_admin_manage on public.transparency_posts
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists compliance_remarks_self_or_admin on public.compliance_remarks;
create policy compliance_remarks_self_or_admin on public.compliance_remarks
for select using (
  public.current_user_is_admin()
  or exists (
    select 1 from public.organization_profiles op
    where op.id = compliance_remarks.organization_id and op.user_id = auth.uid()
  )
);

drop policy if exists compliance_remarks_admin_manage on public.compliance_remarks;
create policy compliance_remarks_admin_manage on public.compliance_remarks
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists notifications_self_or_admin on public.notifications;
create policy notifications_self_or_admin on public.notifications
for all using (public.current_user_is_admin() or user_id = auth.uid()) with check (public.current_user_is_admin() or user_id = auth.uid());

drop policy if exists activity_logs_admin_only on public.activity_logs;
create policy activity_logs_admin_only on public.activity_logs
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

-- Legacy compatibility policies
drop policy if exists organizations_public_read on public.organizations;
create policy organizations_public_read on public.organizations
for select using (true);

drop policy if exists organizations_admin_manage on public.organizations;
create policy organizations_admin_manage on public.organizations
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists programs_public_read on public.programs;
create policy programs_public_read on public.programs
for select using (true);

drop policy if exists programs_admin_manage on public.programs;
create policy programs_admin_manage on public.programs
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists events_public_read on public.events;
create policy events_public_read on public.events
for select using (true);

drop policy if exists events_admin_manage on public.events;
create policy events_admin_manage on public.events
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists disclosure_documents_public_read on public.disclosure_documents;
create policy disclosure_documents_public_read on public.disclosure_documents
for select using (true);

drop policy if exists disclosure_documents_admin_manage on public.disclosure_documents;
create policy disclosure_documents_admin_manage on public.disclosure_documents
for all using (public.current_user_is_admin()) with check (public.current_user_is_admin());

-- ============================================================================
-- Storage Buckets
-- ============================================================================

insert into storage.buckets (id, name, public)
values
  ('organization-documents', 'organization-documents', false),
  ('budget-request-files', 'budget-request-files', false),
  ('liquidation-report-files', 'liquidation-report-files', false),
  ('template-files', 'template-files', false),
  ('transparency-attachments', 'transparency-attachments', true)
on conflict (id) do update set public = excluded.public;

-- ============================================================================
-- Storage Policies
-- ============================================================================

drop policy if exists organization_documents_manage_own on storage.objects;
create policy organization_documents_manage_own on storage.objects
for all using (
  bucket_id = 'organization-documents'
  and (public.current_user_is_admin() or owner = auth.uid())
) with check (
  bucket_id = 'organization-documents'
  and (public.current_user_is_admin() or owner = auth.uid())
);

drop policy if exists organization_documents_read_portal on storage.objects;
create policy organization_documents_read_portal on storage.objects
for select using (bucket_id = 'organization-documents');

drop policy if exists budget_request_files_manage_own on storage.objects;
create policy budget_request_files_manage_own on storage.objects
for all using (
  bucket_id = 'budget-request-files'
  and (public.current_user_is_admin() or owner = auth.uid())
) with check (
  bucket_id = 'budget-request-files'
  and (public.current_user_is_admin() or owner = auth.uid())
);

drop policy if exists budget_request_files_read_portal on storage.objects;
create policy budget_request_files_read_portal on storage.objects
for select using (bucket_id = 'budget-request-files');

drop policy if exists liquidation_report_files_manage_own on storage.objects;
create policy liquidation_report_files_manage_own on storage.objects
for all using (
  bucket_id = 'liquidation-report-files'
  and (public.current_user_is_admin() or owner = auth.uid())
) with check (
  bucket_id = 'liquidation-report-files'
  and (public.current_user_is_admin() or owner = auth.uid())
);

drop policy if exists liquidation_report_files_read_portal on storage.objects;
create policy liquidation_report_files_read_portal on storage.objects
for select using (bucket_id = 'liquidation-report-files');

drop policy if exists template_files_admin_manage on storage.objects;
create policy template_files_admin_manage on storage.objects
for all using (bucket_id = 'template-files')
with check (bucket_id = 'template-files');

drop policy if exists transparency_attachments_read_public on storage.objects;
create policy transparency_attachments_read_public on storage.objects
for select using (bucket_id = 'transparency-attachments');

drop policy if exists transparency_attachments_admin_manage on storage.objects;
create policy transparency_attachments_admin_manage on storage.objects
for all using (bucket_id = 'transparency-attachments' and public.current_user_is_admin())
with check (bucket_id = 'transparency-attachments' and public.current_user_is_admin());

-- ============================================================================
-- Seed Data
-- ============================================================================

insert into public.roles (code, label, description)
values
  ('admin', 'Admin', 'LYDO/PCYDO admin user.'),
  ('organization_user', 'Organization User', 'Authenticated organization member.'),
  ('youth', 'Youth', 'Compatibility role for existing auth flows.')
on conflict (code) do update set label = excluded.label, description = excluded.description;

insert into public.barangays (name)
values
  ('San Antonio'),
  ('Rosario'),
  ('Manggahan')
on conflict (name) do nothing;

insert into public.required_document_types (
  name,
  description,
  required_year,
  is_required,
  template_url,
  template_description,
  sort_order,
  is_active
)
values
  ('Constitution and By-Laws', 'Upload the signed constitution and by-laws.', 2026, true, '#constitution-bylaws-template', 'Template placeholder for the constitutional packet.', 1, true),
  ('2026 NYC YORP Registration Form (Form B)', 'Use the current Form B upload slot.', 2026, true, '#form-b-template', 'Template placeholder for Form B.', 2, true),
  ('2026 YORP Directory of Officers and Adviser', 'List the officers and adviser for the year.', 2026, true, '#officers-adviser-template', 'Template placeholder for the officers list.', 3, true),
  ('2026 YORP List of Members in Good Standing', 'Upload the current list of members in good standing.', 2026, true, '#members-template', 'Template placeholder for the members list.', 4, true),
  ('Pasig City YORP Registration Form (Form A)', 'Official Pasig City Form A requirement.', 2026, true, '#form-a-template', 'Template placeholder for Form A.', 5, true),
  ('PCYDO YORP Data Request Form', 'PCYDO data request form requirement.', 2026, true, '#data-request-template', 'Template placeholder for the PCYDO request form.', 6, true)
on conflict (name) do update
  set description = excluded.description,
      required_year = excluded.required_year,
      is_required = excluded.is_required,
      template_url = excluded.template_url,
      template_description = excluded.template_description,
      sort_order = excluded.sort_order,
      is_active = excluded.is_active;

insert into public.policy_versions (version, title, terms_content, privacy_content, is_active, effective_date)
values (
  '2026-06',
  'LYDO Connect Terms and Privacy',
  'Terms of service placeholder for the organization portal.',
  'Privacy policy placeholder for the organization portal.',
  true,
  current_date
)
on conflict (version) do update
  set title = excluded.title,
      terms_content = excluded.terms_content,
      privacy_content = excluded.privacy_content,
      is_active = excluded.is_active,
      effective_date = excluded.effective_date;

insert into public.admin_accounts (username, password_hash, email, display_name, is_active)
values (
  'lydoadmin',
  extensions.crypt('lydoadminnpassword', extensions.gen_salt('bf')),
  'lydoadmin@lydo-connect.local',
  'Admin User',
  true
)
on conflict (username) do update
  set password_hash = extensions.crypt('lydoadminnpassword', extensions.gen_salt('bf')),
      email = excluded.email,
      display_name = excluded.display_name,
      is_active = excluded.is_active,
      updated_at = now();
