import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "1.25rem",
        lg: "2rem",
      },
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        heading: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        segoe: ['"Segoe UI"', 'system-ui', 'sans-serif'],
        cascadia: ['"Cascadia Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'public-fs-hero': '36px',
        'public-fs-title-page': '28px',
        'public-fs-subtitle-sm': '18px',
        'public-fs-subheading-sm': '16px',
        'public-fs-body-md': '16px',
        'public-fs-body-sm': '14px',
        'public-fs-scale-01': '12px',
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        "surface-hover": "hsl(var(--surface-hover))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          hover: "hsl(var(--primary-hover))",
          active: "hsl(var(--primary-active))",
          strong: "hsl(var(--primary-strong))",
          soft: "hsl(var(--primary-soft))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        brand: {
          deepBlue: "hsl(var(--brand-deep-blue))",
          midBlue: "hsl(var(--brand-mid-blue))",
          skGold: "hsl(var(--brand-sk-gold))",
          skRed: "hsl(var(--brand-sk-red))",
        },
        user: {
          pageBg: "hsl(var(--user-page-bg))",
          surface: "hsl(var(--user-surface))",
          border: "hsl(var(--user-border))",
          navDark: "hsl(var(--user-nav-dark))",
          heading: "hsl(var(--user-heading))",
          link: "hsl(var(--user-link))",
          body: "hsl(var(--user-body))",
          meta: "hsl(var(--user-meta))",
          onDark: "hsl(var(--user-on-dark))",
          activeOnDark: "hsl(var(--user-active-on-dark))",
        },
        admin: {
          pageBg: "hsl(var(--admin-page-bg))",
          surface: "hsl(var(--admin-surface))",
          border: "hsl(var(--admin-border))",
          navDark: "hsl(var(--admin-nav-dark))",
          heading: "hsl(var(--admin-heading))",
          link: "hsl(var(--admin-link))",
          body: "hsl(var(--admin-body))",
          meta: "hsl(var(--admin-meta))",
          onDark: "hsl(var(--admin-on-dark))",
          activeOnDark: "hsl(var(--admin-active-on-dark))",
        },
        "public-nav-bg": "var(--public-nav-bg)",
        "public-text-brand": "var(--public-text-brand)",
        "public-border-brand": "var(--public-border-brand)",
        "public-bg-brand": "var(--public-bg-brand)",
        "public-bg-brand-hover": "var(--public-bg-brand-hover)",
        "public-bg-brand-subtle": "var(--public-bg-brand-subtle)",
        "public-text-on-brand": "var(--public-text-on-brand)",
        "public-text-secondary": "var(--public-text-secondary)",
        "public-text-neutral-on-neutral": "var(--public-text-neutral-on-neutral)",
        "public-gradient-end": "var(--public-gradient-end)",
        "public-bg-section": "var(--public-bg-section)",
        "public-bg-secondary-100": "var(--public-bg-secondary-100)",
        "public-bg-secondary-subtle": "var(--public-bg-secondary-subtle)",
        "public-text-brand-secondary": "var(--public-text-brand-secondary)",
        "public-bg-tertiary-100": "var(--public-bg-tertiary-100)",
        "public-border-neutral-tertiary": "var(--public-border-neutral-tertiary)",
        "public-text-neutral-default": "var(--public-text-neutral-default)",
        "public-border-default": "var(--public-border-default)",
        "text-default": "hsl(var(--text-default))",
        "bg-info-tertiary": "hsl(var(--bg-info-tertiary))",
        "icon-danger-secondary": "hsl(var(--icon-danger-secondary))",
        "text-warning-secondary": "hsl(var(--text-warning-secondary))",
        "text-disabled": "hsl(var(--text-disabled))",
        "danger-subtle": "hsl(var(--danger-subtle))",
        "border-default": "hsl(var(--border-default))",
        "border-warning-subtle": "hsl(var(--border-warning-subtle))",
        "bg-danger-default": "hsl(var(--bg-danger-default))",
        "bg-info-secondary": "hsl(var(--bg-info-secondary))",
        "icon-info-secondary": "hsl(var(--icon-info-secondary))",
        "bg-neutral-subtle": "hsl(var(--bg-neutral-subtle))",
        "bg-warning-default": "hsl(var(--bg-warning-default))",
        "bg-success-default": "hsl(var(--bg-success-default))",
        "bg-success-subtle": "hsl(var(--bg-success-subtle))",
        "border-success-subtle": "hsl(var(--border-success-subtle))",
        "text-neutral-tertiary": "hsl(var(--text-neutral-tertiary))",
        "bg-reference-chip": "hsl(var(--bg-reference-chip))",
        "border-reference-chip": "hsl(var(--border-reference-chip))",
        "text-reference": "hsl(var(--text-reference))",
        "border-tertiary-200": "hsl(var(--border-tertiary-200))",
        "text-tertiary-800": "hsl(var(--text-tertiary-800))",
        "brand-secondary-100": "hsl(var(--brand-secondary-100))",
        "border-brand-secondary": "hsl(var(--border-brand-secondary))",
        "border-info-tertiary": "hsl(var(--border-info-tertiary))",
        "border-closed-subtle": "hsl(var(--border-closed-subtle))",
        "bg-brand-hover": "hsl(var(--bg-brand-hover))",
        "bg-panel-subtle": "hsl(var(--bg-panel-subtle))",
        "gray-100": "hsl(var(--gray-100))",
        "brand-info-subtle": "hsl(var(--brand-info-subtle))",
        "brand-info-border": "hsl(var(--brand-info-border))",
        "positive-secondary": "hsl(var(--positive-secondary))",
        "text-positive-strong": "hsl(var(--text-positive-strong))",
        "text-danger-strong": "hsl(var(--text-danger-strong))",
        "text-neutral-secondary": "hsl(var(--text-neutral-secondary))",
        "text-info-strong": "hsl(var(--text-info-strong))",
        "bg-warning-subtle": "hsl(var(--bg-warning-subtle))",
        "bg-tertiary-subtle": "hsl(var(--bg-tertiary-subtle))",
        "border-panel-subtle": "hsl(var(--border-panel-subtle))",
        "bg-progress-track": "hsl(var(--bg-progress-track))",
        "bg-mandatory-subtle": "hsl(var(--bg-mandatory-subtle))",
        "border-mandatory-subtle": "hsl(var(--border-mandatory-subtle))",
        "text-mandatory": "hsl(var(--text-mandatory))",
        "bg-partnership-subtle": "hsl(var(--bg-partnership-subtle))",
        "border-partnership-subtle": "hsl(var(--border-partnership-subtle))",
        "text-partnership": "hsl(var(--text-partnership))",
        "bg-pink-subtle": "hsl(var(--bg-pink-subtle))",
        "border-pink-subtle": "hsl(var(--border-pink-subtle))",
        "text-pink": "hsl(var(--text-pink))",
        "icon-neutral-strong": "hsl(var(--icon-neutral-strong))",
        "neutral-hover-subtle": "hsl(var(--neutral-hover-subtle))",
        "info-panel-subtle": "hsl(var(--info-panel-subtle))",
        "segmented-control-bg": "hsl(var(--segmented-control-bg))",
        "segmented-control-border": "hsl(var(--segmented-control-border))",
        "segmented-control-inactive-text": "hsl(var(--segmented-control-inactive-text))",
        "role-pink-bg": "hsl(var(--role-pink-bg))",
        "role-pink-border": "hsl(var(--role-pink-border))",
        "role-pink-text": "hsl(var(--role-pink-text))",
        "role-blue-bg": "hsl(var(--role-blue-bg))",
        "role-blue-border": "hsl(var(--role-blue-border))",
        "role-blue-text": "hsl(var(--role-blue-text))",
        "status-active-border": "hsl(var(--status-active-border))",
        "access-pill-bg": "hsl(var(--access-pill-bg))",
        "access-pill-border": "hsl(var(--access-pill-border))",
        "status-danger-border": "hsl(var(--status-danger-border))",
        "status-warning-border": "hsl(var(--status-warning-border))",
        "status-danger-border-strong": "hsl(var(--status-danger-border-strong))",
        "warning-default": "hsl(var(--bg-warning-default))",
        "warning-hover": "hsl(var(--bg-warning-hover))",
        semantic: {
          success: "hsl(var(--semantic-success))",
          warning: "hsl(var(--semantic-warning))",
          danger: "hsl(var(--semantic-danger))",
          infoAdmin: "hsl(var(--semantic-info-admin))",
          infoUser: "hsl(var(--semantic-info-user))",
          disabled: "hsl(var(--semantic-disabled))",
          placeholder: "hsl(var(--semantic-placeholder))",
        },
      },
      boxShadow: {
        "public-nav": "var(--public-nav-shadow)",
        "public-card": "var(--public-card-shadow)",
        "public-overview-card": "var(--public-overview-card-shadow)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
